<?php

namespace Database\Seeders;

use App\Models\PermissionType;
use Illuminate\Database\Seeder;

class PermissionTypeSeeder extends Seeder
{
    public function run(): void
    {
        $types = [
            [
                'name' => 'Permiso administrativo',
                'description' => 'Permiso administrativo general.',
                'requires_attachment' => false,
                'allows_with_pay' => true,
                'allows_without_pay' => false,
                'allows_hourly' => true,
                'allows_half_day' => true,
                'requires_manager_approval' => true,
                'requires_direction_approval' => false,
                'requires_hr_approval' => true,
                'affects_salary' => false,
                'affects_attendance' => true,
                'requires_replacement' => false,
            ],
            [
                'name' => 'Permiso personal',
                'description' => 'Permiso por motivos personales.',
                'requires_attachment' => false,
                'allows_with_pay' => true,
                'allows_without_pay' => true,
                'allows_hourly' => true,
                'allows_half_day' => true,
                'requires_manager_approval' => true,
                'requires_direction_approval' => false,
                'requires_hr_approval' => true,
                'affects_salary' => false,
                'affects_attendance' => true,
                'requires_replacement' => false,
            ],
            [
                'name' => 'Permiso médico',
                'description' => 'Permiso por atención o situación médica.',
                'requires_attachment' => true,
                'allows_with_pay' => true,
                'allows_without_pay' => true,
                'allows_hourly' => false,
                'allows_half_day' => false,
                'requires_manager_approval' => true,
                'requires_direction_approval' => false,
                'requires_hr_approval' => true,
                'affects_salary' => false,
                'affects_attendance' => true,
                'requires_replacement' => false,
            ],
            [
                'name' => 'Permiso por trámite',
                'description' => 'Permiso por diligencias o trámites.',
                'requires_attachment' => false,
                'allows_with_pay' => true,
                'allows_without_pay' => true,
                'allows_hourly' => true,
                'allows_half_day' => true,
                'requires_manager_approval' => true,
                'requires_direction_approval' => false,
                'requires_hr_approval' => true,
                'affects_salary' => false,
                'affects_attendance' => true,
                'requires_replacement' => false,
            ],
            [
                'name' => 'Permiso por emergencia',
                'description' => 'Permiso por emergencia debidamente justificada.',
                'requires_attachment' => false,
                'allows_with_pay' => true,
                'allows_without_pay' => true,
                'allows_hourly' => true,
                'allows_half_day' => true,
                'requires_manager_approval' => true,
                'requires_direction_approval' => true,
                'requires_hr_approval' => true,
                'minimum_notice_days' => 0,
                'allows_retroactive' => true,
                'affects_salary' => false,
                'affects_attendance' => true,
                'requires_replacement' => true,
            ],
            [
                'name' => 'Permiso por fallecimiento',
                'description' => 'Permiso por fallecimiento de familiar.',
                'requires_attachment' => true,
                'allows_with_pay' => true,
                'allows_without_pay' => false,
                'allows_hourly' => false,
                'allows_half_day' => false,
                'requires_manager_approval' => true,
                'requires_direction_approval' => true,
                'requires_hr_approval' => true,
                'max_days' => 5,
                'affects_salary' => false,
                'affects_attendance' => true,
                'requires_replacement' => true,
            ],
            [
                'name' => 'Permiso por nacimiento',
                'description' => 'Permiso por nacimiento.',
                'requires_attachment' => true,
                'allows_with_pay' => true,
                'allows_without_pay' => false,
                'allows_hourly' => false,
                'allows_half_day' => false,
                'requires_manager_approval' => true,
                'requires_direction_approval' => true,
                'requires_hr_approval' => true,
                'max_days' => 5,
                'affects_salary' => false,
                'affects_attendance' => true,
                'requires_replacement' => true,
            ],
            [
                'name' => 'Permiso por matrimonio o unión civil',
                'description' => 'Permiso especial por matrimonio o unión civil.',
                'requires_attachment' => true,
                'allows_with_pay' => true,
                'allows_without_pay' => false,
                'allows_hourly' => false,
                'allows_half_day' => false,
                'requires_manager_approval' => true,
                'requires_direction_approval' => true,
                'requires_hr_approval' => true,
                'max_days' => 5,
                'affects_salary' => false,
                'affects_attendance' => true,
                'requires_replacement' => true,
            ],
            [
                'name' => 'Permiso sindical',
                'description' => 'Permiso sindical, cuando corresponda.',
                'requires_attachment' => true,
                'allows_with_pay' => true,
                'allows_without_pay' => false,
                'allows_hourly' => true,
                'allows_half_day' => true,
                'requires_manager_approval' => true,
                'requires_direction_approval' => true,
                'requires_hr_approval' => true,
                'affects_salary' => false,
                'affects_attendance' => true,
                'requires_replacement' => false,
            ],
            [
                'name' => 'Permiso por capacitación',
                'description' => 'Permiso por capacitación autorizada.',
                'requires_attachment' => true,
                'allows_with_pay' => true,
                'allows_without_pay' => false,
                'allows_hourly' => false,
                'allows_half_day' => false,
                'requires_manager_approval' => true,
                'requires_direction_approval' => true,
                'requires_hr_approval' => true,
                'affects_salary' => false,
                'affects_attendance' => true,
                'requires_replacement' => true,
            ],
            [
                'name' => 'Permiso por citación judicial',
                'description' => 'Permiso por citación judicial u orden equivalente.',
                'requires_attachment' => true,
                'allows_with_pay' => true,
                'allows_without_pay' => false,
                'allows_hourly' => true,
                'allows_half_day' => true,
                'requires_manager_approval' => true,
                'requires_direction_approval' => true,
                'requires_hr_approval' => true,
                'affects_salary' => false,
                'affects_attendance' => true,
                'requires_replacement' => false,
            ],
            [
                'name' => 'Permiso especial definido por Dirección',
                'description' => 'Permiso especial definido por Dirección.',
                'requires_attachment' => false,
                'allows_with_pay' => true,
                'allows_without_pay' => true,
                'allows_hourly' => true,
                'allows_half_day' => true,
                'requires_manager_approval' => true,
                'requires_direction_approval' => true,
                'requires_hr_approval' => true,
                'allows_retroactive' => true,
                'affects_salary' => false,
                'affects_attendance' => true,
                'requires_replacement' => true,
            ],
            [
                'name' => 'Permiso sin goce de remuneraciones',
                'description' => 'Permiso sin goce de remuneraciones.',
                'requires_attachment' => false,
                'allows_with_pay' => false,
                'allows_without_pay' => true,
                'allows_hourly' => false,
                'allows_half_day' => false,
                'requires_manager_approval' => true,
                'requires_direction_approval' => true,
                'requires_hr_approval' => true,
                'affects_salary' => true,
                'affects_attendance' => true,
                'requires_replacement' => true,
            ],
            [
                'name' => 'Permiso con goce de remuneraciones',
                'description' => 'Permiso con goce de remuneraciones.',
                'requires_attachment' => false,
                'allows_with_pay' => true,
                'allows_without_pay' => false,
                'allows_hourly' => true,
                'allows_half_day' => true,
                'requires_manager_approval' => true,
                'requires_direction_approval' => true,
                'requires_hr_approval' => true,
                'affects_salary' => false,
                'affects_attendance' => true,
                'requires_replacement' => true,
            ],
        ];

        foreach ($types as $type) {
            PermissionType::query()->updateOrCreate(
                ['name' => $type['name']],
                array_merge($type, ['active' => true]),
            );
        }
    }
}
