<?php

namespace Database\Seeders;

use App\Models\Permission;
use App\Models\PermissionGroup;
use App\Models\SystemModule;
use Illuminate\Database\Seeder;

class PermissionGroupSeeder extends Seeder
{
    public function run(): void
    {
        $modulesBySlug = SystemModule::query()->get()->keyBy('slug');
        $permissionsBySlug = Permission::query()->where('active', true)->get()->keyBy('slug');

        foreach (self::definitions() as $index => $definition) {
            $group = PermissionGroup::query()->updateOrCreate(
                ['slug' => $definition['slug']],
                [
                    'system_module_id' => $modulesBySlug->get($definition['module_slug'])?->id,
                    'name' => $definition['name'],
                    'description' => $definition['description'],
                    'sort_order' => $definition['sort_order'] ?? (($index + 1) * 10),
                    'active' => true,
                ],
            );

            $permissionIds = collect($definition['permissions'])
                ->map(fn (string $slug) => $permissionsBySlug->get($slug)?->id)
                ->filter()
                ->values()
                ->all();

            $group->permissions()->sync($permissionIds);
        }
    }

    /**
     * @return array<int, array{slug:string,module_slug:string,name:string,description:string,sort_order:int,permissions:array<int,string>}>
     */
    public static function definitions(): array
    {
        return [
            [
                'slug' => 'general_dashboard_reportes',
                'module_slug' => 'dashboard',
                'name' => 'Dashboard y reportes generales',
                'description' => 'Acceso base a dashboard, reportes generales y exportaciones transversales.',
                'sort_order' => 10,
                'permissions' => [
                    'ver_dashboard',
                    'ver_reportes',
                    'exportar_reportes',
                ],
            ],
            [
                'slug' => 'sitio_publico',
                'module_slug' => 'public_site',
                'name' => 'Sitio publico',
                'description' => 'Gestion de noticias, eventos y mensajes recibidos desde el sitio publico.',
                'sort_order' => 20,
                'permissions' => [
                    'ver_noticias',
                    'gestionar_noticias',
                    'ver_eventos',
                    'gestionar_eventos',
                    'ver_contactos_sitio',
                    'gestionar_contactos_sitio',
                ],
            ],
            [
                'slug' => 'comunicaciones_internas',
                'module_slug' => 'internal_communications',
                'name' => 'Comunicaciones internas',
                'description' => 'Avisos internos segmentados por roles, lectura y confirmacion de recepcion.',
                'sort_order' => 25,
                'permissions' => [
                    'ver_comunicaciones_internas',
                    'gestionar_comunicaciones_internas',
                ],
            ],
            [
                'slug' => 'estudiantes',
                'module_slug' => 'students',
                'name' => 'Estudiantes',
                'description' => 'Ficha de estudiantes, cursos, anos academicos, matriculas y promocion anual.',
                'sort_order' => 30,
                'permissions' => [
                    'ver_estudiantes',
                    'crear_estudiantes',
                    'editar_estudiantes',
                    'eliminar_estudiantes',
                    'ver_ficha_estudiante',
                    'administrar_anos_academicos',
                    'administrar_cursos_academicos',
                    'gestionar_matriculas_estudiantes',
                    'promover_estudiantes',
                ],
            ],
            [
                'slug' => 'horarios_docentes',
                'module_slug' => 'schedule',
                'name' => 'Horarios docentes',
                'description' => 'Consulta, configuracion y edicion de horarios, jornadas, planes de estudio y carga docente.',
                'sort_order' => 40,
                'permissions' => [
                    'ver_horarios',
                    'editar_horarios',
                    'configurar_horarios',
                    'configurar_jornadas',
                    'configurar_plan_estudio',
                    'configurar_contratos_docentes',
                    'forzar_excepciones_horario',
                    'ver_reportes_carga_horaria',
                ],
            ],
            [
                'slug' => 'porteria',
                'module_slug' => 'porter',
                'name' => 'Porteria',
                'description' => 'Control de retiros, objetos, mercaderia, visitas, proveedores, bitacora y llaves.',
                'sort_order' => 50,
                'permissions' => [
                    'ver_porteria',
                    'ver_historial_porteria',
                    'registrar_retiro_porteria',
                    'autorizar_retiros_porteria',
                    'registrar_objetos_porteria',
                    'entregar_objetos_porteria',
                    'registrar_mercaderia_porteria',
                    'entregar_mercaderia_porteria',
                    'registrar_visitas_porteria',
                    'registrar_proveedores_porteria',
                    'registrar_bitacora_porteria',
                    'gestionar_llaves_porteria',
                    'exportar_reportes_porteria',
                ],
            ],
            [
                'slug' => 'funcionarios',
                'module_slug' => 'staff',
                'name' => 'Funcionarios',
                'description' => 'Ficha de funcionarios, departamentos, documentos y exportaciones de personal.',
                'sort_order' => 60,
                'permissions' => [
                    'ver_funcionarios',
                    'gestionar_funcionarios',
                    'eliminar_funcionarios',
                    'subir_documentos_funcionarios',
                    'exportar_funcionarios',
                    'administrar_departamentos',
                ],
            ],
            [
                'slug' => 'permisos_personal',
                'module_slug' => 'staff_permissions',
                'name' => 'Permisos del personal',
                'description' => 'Solicitudes, revision, aprobacion, documentos, reemplazos, destinatarios y reportes de permisos.',
                'sort_order' => 70,
                'permissions' => [
                    'ver_permisos_personal',
                    'solicitar_permisos_personal',
                    'revisar_permisos_equipo',
                    'aprobar_permisos_direccion',
                    'revisar_permisos_rrhh',
                    'administrar_tipos_permisos_personal',
                    'administrar_destinatarios_permisos_personal',
                    'exportar_permisos_personal',
                    'validar_documentos_permisos_personal',
                    'gestionar_reemplazos_permisos_personal',
                    'ver_reportes_permisos_personal',
                ],
            ],
            [
                'slug' => 'tareas',
                'module_slug' => 'tasks',
                'name' => 'Tareas',
                'description' => 'Backlog, gestion de tareas propias/equipo y asignadores autorizados.',
                'sort_order' => 80,
                'permissions' => [
                    'ver_tareas',
                    'gestionar_tareas',
                    'ver_tareas_equipo',
                    'administrar_asignadores_tareas',
                ],
            ],
            [
                'slug' => 'contratos',
                'module_slug' => 'contracts',
                'name' => 'Contratos',
                'description' => 'Gestion de contratos, plantillas, clausulas, firmas y exportacion de documentos.',
                'sort_order' => 90,
                'permissions' => [
                    'ver_contratos',
                    'gestionar_contratos',
                    'eliminar_contratos',
                    'exportar_contratos',
                    'administrar_plantillas_contrato',
                    'administrar_clausulas_contrato',
                    'administrar_firmas_contrato',
                    'editar_contratos_firmados',
                ],
            ],
            [
                'slug' => 'enfermeria',
                'module_slug' => 'infirmary',
                'name' => 'Enfermeria',
                'description' => 'Atenciones, ficha medica, inventario, medicamentos, accidentes y reportes de enfermeria.',
                'sort_order' => 100,
                'permissions' => [
                    'ver_salud',
                    'ver_enfermeria',
                    'crear_atenciones_enfermeria',
                    'editar_atenciones_enfermeria',
                    'eliminar_atenciones_enfermeria',
                    'exportar_enfermeria',
                    'administrar_inventario_enfermeria',
                    'administrar_medicamentos_enfermeria',
                    'administrar_catalogos_enfermeria',
                    'gestionar_accidentes_enfermeria',
                    'ver_reportes_enfermeria',
                ],
            ],
            [
                'slug' => 'psicologia',
                'module_slug' => 'psychology',
                'name' => 'Psicologia',
                'description' => 'Acceso legado al modulo o vistas de psicologia.',
                'sort_order' => 110,
                'permissions' => [
                    'ver_psicologia',
                ],
            ],
            [
                'slug' => 'convivencia_escolar',
                'module_slug' => 'convivencia',
                'name' => 'Convivencia Escolar',
                'description' => 'Dashboard, plan, casos, denuncias, protocolos, entrevistas, medidas, derivaciones y reportes.',
                'sort_order' => 120,
                'permissions' => [
                    'ver_convivencia',
                    'ver_dashboard_convivencia',
                    'gestionar_plan_convivencia',
                    'crear_casos_convivencia',
                    'ver_casos_convivencia',
                    'editar_casos_convivencia',
                    'cerrar_casos_convivencia',
                    'ver_casos_sensibles_convivencia',
                    'gestionar_denuncias_convivencia',
                    'gestionar_protocolos_convivencia',
                    'activar_protocolos_convivencia',
                    'gestionar_entrevistas_convivencia',
                    'gestionar_medidas_formativas_convivencia',
                    'gestionar_derivaciones_internas_convivencia',
                    'gestionar_derivaciones_externas_convivencia',
                    'ver_sociogramas_convivencia',
                    'gestionar_sociogramas_convivencia',
                    'ver_reportes_curso_convivencia',
                    'gestionar_bitacora_inspectoria_convivencia',
                    'exportar_reportes_convivencia',
                    'administrar_configuraciones_convivencia',
                ],
            ],
            [
                'slug' => 'prevencion_riesgos',
                'module_slug' => 'risk_prevention',
                'name' => 'Prevencion de Riesgos',
                'description' => 'Gestion de extintores, accidentes, emergencias, EPP, capacitaciones, documentos y reportes.',
                'sort_order' => 130,
                'permissions' => [
                    'ver_prevencion_riesgos',
                    'gestionar_prevencion_riesgos',
                    'exportar_prevencion_riesgos',
                ],
            ],
            [
                'slug' => 'mantencion',
                'module_slug' => 'maintenance',
                'name' => 'Mantencion',
                'description' => 'Ordenes de trabajo, visitas, carga de trabajo y plan anual de mantencion.',
                'sort_order' => 140,
                'permissions' => [
                    'ver_mantencion',
                    'crear_ot',
                    'editar_ot',
                    'cerrar_ot',
                    'ver_reportes_mantencion',
                    'exportar_mantencion',
                    'ver_visitas_mantencion',
                    'gestionar_visitas_mantencion',
                    'ver_plan_anual_mantencion',
                    'gestionar_plan_anual_mantencion',
                ],
            ],
            [
                'slug' => 'inventario',
                'module_slug' => 'inventory',
                'name' => 'Inventario',
                'description' => 'Bienes, movimientos, bajas, categorias, documentos, etiquetas, proveedores y reportes.',
                'sort_order' => 150,
                'permissions' => [
                    'ver_inventario',
                    'crear_inventario',
                    'editar_inventario',
                    'eliminar_inventario',
                    'dar_baja_inventario',
                    'mover_inventario',
                    'ver_reportes_inventario',
                    'exportar_inventario',
                    'administrar_categorias_inventario',
                    'subir_documentos_inventario',
                    'eliminar_documentos_inventario',
                    'imprimir_etiquetas_inventario',
                ],
            ],
            [
                'slug' => 'dependencias_reservas',
                'module_slug' => 'spaces',
                'name' => 'Dependencias y reservas',
                'description' => 'Dependencias, tipos, aprobadores, reservas, calendario y estadisticas de espacios.',
                'sort_order' => 160,
                'permissions' => [
                    'ver_dependencias',
                    'crear_dependencias',
                    'editar_dependencias',
                    'eliminar_dependencias',
                    'ver_reservas',
                    'crear_reservas',
                    'editar_reservas',
                    'cancelar_reservas',
                    'aprobar_reservas',
                    'rechazar_reservas',
                    'exportar_reservas',
                    'administrar_calendario',
                    'ver_estadisticas_espacios',
                    'exportar_estadisticas_espacios',
                ],
            ],
            [
                'slug' => 'seguridad_nochero',
                'module_slug' => 'security',
                'name' => 'Control de Nochero',
                'description' => 'Turnos, rondas, novedades de seguridad y exportaciones del modulo.',
                'sort_order' => 170,
                'permissions' => [
                    'ver_rondas_seguridad',
                    'gestionar_turnos_nochero',
                    'registrar_rondas_seguridad',
                    'gestionar_novedades_rondas',
                    'exportar_rondas_seguridad',
                ],
            ],
            [
                'slug' => 'calendario_fechas_relevantes',
                'module_slug' => 'relevant_calendar',
                'name' => 'Calendario de fechas relevantes',
                'description' => 'Eventos institucionales, tipos, instituciones, administracion y exportacion del calendario relevante.',
                'sort_order' => 180,
                'permissions' => [
                    'ver_calendario_fechas_relevantes',
                    'ver_todo_calendario_fechas_relevantes',
                    'gestionar_calendario_fechas_relevantes_departamento',
                    'administrar_calendario_fechas_relevantes',
                    'administrar_tipos_calendario_fechas_relevantes',
                    'administrar_instituciones_calendario_fechas_relevantes',
                    'exportar_calendario_fechas_relevantes',
                ],
            ],
            [
                'slug' => 'pme_sep',
                'module_slug' => 'pme_sep',
                'name' => 'PME / SEP',
                'description' => 'Planificacion PME/SEP, ingresos, estudiantes, objetivos, estrategias, acciones, evidencias y reportes.',
                'sort_order' => 190,
                'permissions' => [
                    'ver_modulo_pme',
                    'crear_pme',
                    'editar_pme',
                    'cerrar_pme',
                    'administrar_ingresos_sep',
                    'ver_estudiantes_prioritarios_sep',
                    'ver_estudiantes_preferentes_sep',
                    'cargar_estudiantes_sep',
                    'crear_objetivos_pme',
                    'editar_objetivos_pme',
                    'crear_estrategias_pme',
                    'editar_estrategias_pme',
                    'crear_indicadores_pme',
                    'medir_indicadores_pme',
                    'crear_acciones_pme',
                    'editar_acciones_pme',
                    'cerrar_acciones_pme',
                    'crear_evidencias_pme',
                    'revisar_evidencias_pme',
                    'aprobar_evidencias_pme',
                    'rechazar_evidencias_pme',
                    'crear_hitos_pme',
                    'registrar_monitoreo_reflexivo_pme',
                    'ver_reportes_pme',
                    'exportar_reportes_pme',
                    'administrar_configuracion_pme',
                ],
            ],
            [
                'slug' => 'biblioteca',
                'module_slug' => 'biblioteca',
                'name' => 'Biblioteca',
                'description' => 'Catalogo, inventario, prestamos, devoluciones, reservas, plan lector, espacios y reportes.',
                'sort_order' => 200,
                'permissions' => [
                    'ver_modulo_biblioteca',
                    'crear_libros_biblioteca',
                    'editar_libros_biblioteca',
                    'eliminar_libros_biblioteca',
                    'administrar_catalogo_biblioteca',
                    'administrar_inventario_biblioteca',
                    'registrar_prestamos_biblioteca',
                    'registrar_devoluciones_biblioteca',
                    'renovar_prestamos_biblioteca',
                    'gestionar_mora_biblioteca',
                    'gestionar_reservas_biblioteca',
                    'gestionar_plan_lector_biblioteca',
                    'gestionar_uso_espacios_biblioteca',
                    'ver_estadisticas_biblioteca',
                    'exportar_reportes_biblioteca',
                ],
            ],
            [
                'slug' => 'centro_apuntes_panol',
                'module_slug' => 'centro_apuntes',
                'name' => 'Centro de Apuntes y Panol',
                'description' => 'Solicitudes de impresion, maquinas, asignaturas, insumos, movimientos, entregas y reportes.',
                'sort_order' => 210,
                'permissions' => [
                    'ver_modulo_centro_apuntes',
                    'crear_solicitud_impresion',
                    'editar_solicitud_impresion',
                    'eliminar_solicitud_impresion',
                    'cambiar_estado_solicitud_impresion',
                    'registrar_entrega_centro_apuntes',
                    'administrar_asignaturas_centro_apuntes',
                    'administrar_maquinas_centro_apuntes',
                    'administrar_inventario_panol',
                    'registrar_movimientos_panol',
                    'aprobar_entregas_panol',
                    'ver_reportes_centro_apuntes',
                    'exportar_reportes_centro_apuntes',
                ],
            ],
            [
                'slug' => 'apoyo_profesional',
                'module_slug' => 'apoyo_profesional',
                'name' => 'Apoyo profesional',
                'description' => 'Atenciones, derivaciones, seguimientos, planes, confidencialidad, configuracion y reportes.',
                'sort_order' => 220,
                'permissions' => [
                    'ver_modulo_apoyo_profesional',
                    'crear_atencion_apoyo_profesional',
                    'editar_atencion_propia_apoyo_profesional',
                    'editar_cualquier_atencion_apoyo_profesional',
                    'eliminar_atencion_apoyo_profesional',
                    'ver_atenciones_propias_apoyo_profesional',
                    'ver_atenciones_equipo_apoyo_profesional',
                    'ver_atenciones_confidenciales_apoyo_profesional',
                    'crear_derivacion_apoyo_profesional',
                    'responder_derivacion_apoyo_profesional',
                    'crear_seguimiento_apoyo_profesional',
                    'cerrar_caso_apoyo_profesional',
                    'crear_plan_apoyo_profesional',
                    'ver_reportes_apoyo_profesional',
                    'exportar_reportes_apoyo_profesional',
                    'administrar_configuracion_apoyo_profesional',
                ],
            ],
            [
                'slug' => 'informatica',
                'module_slug' => 'informatica',
                'name' => 'Informatica',
                'description' => 'Equipos, prestamos, devoluciones, mantenciones y reportes del area informatica.',
                'sort_order' => 230,
                'permissions' => [
                    'informatica.ver',
                    'informatica.dashboard',
                    'informatica.equipos.ver',
                    'informatica.equipos.crear',
                    'informatica.equipos.editar',
                    'informatica.equipos.eliminar',
                    'informatica.prestamos.ver',
                    'informatica.prestamos.crear',
                    'informatica.prestamos.devolver',
                    'informatica.prestamos.cancelar',
                    'informatica.mantenciones.ver',
                    'informatica.mantenciones.crear',
                    'informatica.mantenciones.editar',
                    'informatica.mantenciones.cerrar',
                    'informatica.reportes.ver',
                ],
            ],
            [
                'slug' => 'contabilidad',
                'module_slug' => 'accounting',
                'name' => 'Contabilidad',
                'description' => 'Presupuesto, centros de costo, cuentas, ingresos, egresos, pagos, conciliacion, impuestos y reportes.',
                'sort_order' => 240,
                'permissions' => [
                    'contabilidad.ver',
                    'contabilidad.dashboard',
                    'contabilidad.presupuesto.ver',
                    'contabilidad.presupuesto.crear',
                    'contabilidad.presupuesto.aprobar',
                    'contabilidad.centros_costo.gestionar',
                    'contabilidad.manual_cuentas.gestionar',
                    'contabilidad.ingresos.gestionar',
                    'contabilidad.egresos.gestionar',
                    'contabilidad.pagos.gestionar',
                    'contabilidad.caja_chica.gestionar',
                    'contabilidad.fondos_rendir.gestionar',
                    'contabilidad.conciliacion.gestionar',
                    'contabilidad.subvenciones.ver',
                    'contabilidad.cheques.gestionar',
                    'contabilidad.facturas.gestionar',
                    'contabilidad.boletas.gestionar',
                    'contabilidad.f29.gestionar',
                    'contabilidad.dj.gestionar',
                    'contabilidad.renta.gestionar',
                    'contabilidad.balance.ver',
                    'contabilidad.reportes.exportar',
                    'contabilidad.admin',
                ],
            ],
            [
                'slug' => 'remuneraciones',
                'module_slug' => 'remuneration',
                'name' => 'Remuneraciones',
                'description' => 'Trabajadores, contratos, parametros, conceptos, movimientos, liquidaciones, pagos, periodos y RR.HH.',
                'sort_order' => 250,
                'permissions' => [
                    'remuneraciones.ver',
                    'remuneraciones.dashboard',
                    'remuneraciones.trabajadores.gestionar',
                    'remuneraciones.contratos.gestionar',
                    'remuneraciones.parametros.gestionar',
                    'remuneraciones.conceptos.gestionar',
                    'remuneraciones.movimientos.gestionar',
                    'remuneraciones.liquidaciones.calcular',
                    'remuneraciones.liquidaciones.aprobar',
                    'remuneraciones.pagos.gestionar',
                    'remuneraciones.contabilidad.centralizar',
                    'remuneraciones.reportes.ver',
                    'remuneraciones.reportes.exportar',
                    'remuneraciones.importar',
                    'remuneraciones.periodos.cerrar',
                    'remuneraciones.rrhh.gestionar',
                    'remuneraciones.admin',
                ],
            ],
            [
                'slug' => 'administracion_sistema',
                'module_slug' => 'settings',
                'name' => 'Administracion del sistema',
                'description' => 'Usuarios, roles, permisos, modulos, cargos y organigrama.',
                'sort_order' => 260,
                'permissions' => [
                    'administrar_usuarios',
                    'administrar_roles',
                    'administrar_permisos',
                    'administrar_modulos',
                    'administrar_cargos',
                    'administrar_organigrama',
                ],
            ],
        ];
    }
}
