<script setup>
import { onMounted, reactive, ref, watch } from "vue";
import axios from "axios";
import Swal from "sweetalert2";

const props = defineProps({ filters: { type: Object, required: true } });
const loading = ref(false); const config = ref({ risk_levels: [], alert_rules: [], absence_reasons: [], financial_parameters: [] });
const editType = ref(""); const saving = ref(false); const selected = ref(null);
const riskForm = reactive({ name: "", minimum_rate: 0, maximum_rate: 100, color: "#405189", icon: "bx-shield", priority: 1, suggested_actions: "", intervention_due_days: 5, active: true, reason: "" });
const ruleForm = reactive({ name: "", description: "", operator: "lt", threshold: 85, evaluation_period: "academic_year", severity: "warning", cooldown_days: 7, response_due_days: 3, auto_create_case: false, active: true, reason: "" });
const financialForm = reactive({ academic_year_id: null, name: "Subvención asistencia", subsidy_type: "general", unit_value: 0, attendance_factor: 1, currency: "CLP", valid_from: "", valid_to: "", source_reference: "", assumptions: "", active: true, reason: "" });

const load = async () => {
  if (!props.filters.academic_year_id) return;
  loading.value = true;
  try { const response = await axios.get("/api/attendance-statistics/configuration", { params: { academic_year_id: props.filters.academic_year_id } }); config.value = response.data; }
  catch (error) { await Swal.fire({ icon: "error", title: "No se pudo cargar la configuración", text: error.response?.data?.message || "Intenta nuevamente." }); }
  finally { loading.value = false; }
};
const editRisk = (item) => { selected.value = item; Object.assign(riskForm, { name: item.name, minimum_rate: Number(item.minimum_rate), maximum_rate: Number(item.maximum_rate), color: item.color, icon: item.icon, priority: item.priority, suggested_actions: item.suggested_actions || "", intervention_due_days: item.intervention_due_days || 5, active: Boolean(item.active), reason: "" }); editType.value = "risk"; };
const editRule = (item) => { selected.value = item; Object.assign(ruleForm, { name: item.name, description: item.description || "", operator: item.operator, threshold: Number(item.threshold), evaluation_period: item.evaluation_period, severity: item.severity, cooldown_days: item.cooldown_days, response_due_days: item.response_due_days, auto_create_case: Boolean(item.auto_create_case), active: Boolean(item.active), reason: "" }); editType.value = "rule"; };
const saveEdit = async () => {
  saving.value = true;
  try {
    const form = editType.value === "risk" ? riskForm : ruleForm;
    const path = editType.value === "risk" ? `risk-levels/${selected.value.id}` : `alert-rules/${selected.value.id}`;
    await axios.put(`/api/attendance-statistics/configuration/${path}`, form); editType.value = ""; await load();
    await Swal.fire({ icon: "success", title: "Configuración actualizada", timer: 1300, showConfirmButton: false });
  } catch (error) { await Swal.fire({ icon: "error", title: "No se pudo guardar", text: error.response?.data?.message || Object.values(error.response?.data?.errors || {}).flat().join(" ") }); }
  finally { saving.value = false; }
};
const saveFinancial = async () => {
  saving.value = true;
  try { await axios.post("/api/attendance-statistics/configuration/financial-parameters", { ...financialForm, valid_to: financialForm.valid_to || null }); await load(); await Swal.fire({ icon: "success", title: "Parámetro registrado", timer: 1300, showConfirmButton: false }); }
  catch (error) { await Swal.fire({ icon: "error", title: "No se pudo registrar", text: error.response?.data?.message || Object.values(error.response?.data?.errors || {}).flat().join(" ") }); }
  finally { saving.value = false; }
};
watch(() => props.filters.academic_year_id, () => { financialForm.academic_year_id = Number(props.filters.academic_year_id); load(); });
onMounted(() => { financialForm.academic_year_id = Number(props.filters.academic_year_id); load(); });
</script>

<template>
  <section class="config-stack" :class="{ 'is-loading': loading }">
    <article class="config-panel"><header><div><span>CLASIFICACIÓN</span><h2>Niveles de riesgo</h2></div></header><div class="config-list"><button v-for="item in config.risk_levels" :key="item.id" type="button" @click="editRisk(item)"><span class="risk-swatch" :style="{ background: item.color }"></span><div><strong>{{ item.name }}</strong><small>{{ Number(item.minimum_rate).toLocaleString('es-CL') }}% a {{ Number(item.maximum_rate).toLocaleString('es-CL') }}%</small></div><span :class="['active-state', { off: !item.active }]">{{ item.active ? 'Activo' : 'Inactivo' }}</span><i class="bx bx-edit-alt"></i></button></div></article>
    <article class="config-panel"><header><div><span>AUTOMATIZACIÓN</span><h2>Reglas de alerta</h2></div></header><div class="config-list"><button v-for="item in config.alert_rules" :key="item.id" type="button" @click="editRule(item)"><i class="bx bx-bell"></i><div><strong>{{ item.name }}</strong><small>{{ item.metric }} {{ item.operator }} {{ Number(item.threshold).toLocaleString('es-CL') }}</small></div><span :class="['active-state', { off: !item.active }]">{{ item.active ? 'Activa' : 'Inactiva' }}</span><i class="bx bx-edit-alt"></i></button></div></article>
    <article class="config-panel"><header><div><span>CATÁLOGO</span><h2>Motivos de ausencia</h2></div></header><div class="reason-grid"><span v-for="reason in config.absence_reasons" :key="reason.id"><i class="bx bx-tag"></i>{{ reason.name }}<b>{{ reason.category }}</b></span></div></article>
    <article class="config-panel"><header><div><span>ESTIMACIÓN</span><h2>Parámetro financiero</h2></div></header><form class="financial-form" @submit.prevent="saveFinancial"><label><span>Nombre</span><input v-model.trim="financialForm.name" class="form-control" required /></label><label><span>Valor unitario</span><input v-model.number="financialForm.unit_value" type="number" min="0" step="0.01" class="form-control" required /></label><label><span>Factor</span><input v-model.number="financialForm.attendance_factor" type="number" min="0" step="0.01" class="form-control" required /></label><label><span>Vigente desde</span><input v-model="financialForm.valid_from" type="date" class="form-control" required /></label><label><span>Fuente</span><input v-model.trim="financialForm.source_reference" class="form-control" required /></label><label class="wide"><span>Supuestos</span><textarea v-model.trim="financialForm.assumptions" class="form-control" rows="2" required></textarea></label><label class="wide"><span>Motivo del cambio</span><input v-model.trim="financialForm.reason" class="form-control" required /></label><button type="submit" class="btn btn-primary" :disabled="saving"><i class="bx bx-save"></i>Registrar</button></form><div v-if="config.financial_parameters.length" class="financial-current"><strong>Vigente:</strong> {{ config.financial_parameters[0].name }} · {{ Number(config.financial_parameters[0].unit_value).toLocaleString('es-CL', { style:'currency', currency: config.financial_parameters[0].currency }) }}</div></article>

    <div v-if="editType" class="config-backdrop" role="dialog" aria-modal="true" @click.self="editType = ''" @keydown.esc="editType = ''"><form class="config-dialog" @submit.prevent="saveEdit"><header><h3>{{ editType === 'risk' ? 'Editar nivel de riesgo' : 'Editar regla de alerta' }}</h3><button type="button" class="icon-btn" title="Cerrar" @click="editType = ''"><i class="bx bx-x"></i></button></header>
      <template v-if="editType === 'risk'"><label><span>Nombre</span><input v-model.trim="riskForm.name" class="form-control" required /></label><div class="two-cols"><label><span>Mínimo</span><input v-model.number="riskForm.minimum_rate" type="number" min="0" max="100" class="form-control" required /></label><label><span>Máximo</span><input v-model.number="riskForm.maximum_rate" type="number" min="0" max="100" class="form-control" required /></label></div><div class="two-cols"><label><span>Color</span><input v-model="riskForm.color" type="color" class="form-control form-control-color" /></label><label><span>Prioridad</span><input v-model.number="riskForm.priority" type="number" min="1" max="100" class="form-control" required /></label></div><label><span>Acciones sugeridas</span><textarea v-model.trim="riskForm.suggested_actions" class="form-control" rows="3"></textarea></label><label class="check-line"><input v-model="riskForm.active" type="checkbox" />Nivel activo</label></template>
      <template v-else><label><span>Nombre</span><input v-model.trim="ruleForm.name" class="form-control" required /></label><label><span>Descripción</span><textarea v-model.trim="ruleForm.description" class="form-control" rows="2"></textarea></label><div class="two-cols"><label><span>Operador</span><select v-model="ruleForm.operator" class="form-select"><option value="lt">Menor que</option><option value="lte">Menor o igual</option><option value="gt">Mayor que</option><option value="gte">Mayor o igual</option><option value="eq">Igual</option></select></label><label><span>Umbral</span><input v-model.number="ruleForm.threshold" type="number" step="0.01" class="form-control" required /></label></div><div class="two-cols"><label><span>Severidad</span><select v-model="ruleForm.severity" class="form-select"><option value="info">Informativa</option><option value="warning">Advertencia</option><option value="critical">Crítica</option></select></label><label><span>Días para respuesta</span><input v-model.number="ruleForm.response_due_days" type="number" min="1" max="365" class="form-control" required /></label></div><label class="check-line"><input v-model="ruleForm.active" type="checkbox" />Regla activa</label></template>
      <label><span>Motivo del cambio</span><textarea v-model.trim="(editType === 'risk' ? riskForm : ruleForm).reason" class="form-control" rows="2" required></textarea></label><footer><button type="button" class="btn btn-light" @click="editType = ''">Cancelar</button><button type="submit" class="btn btn-primary" :disabled="saving"><i class="bx bx-save"></i>Guardar</button></footer>
    </form></div>
  </section>
</template>

<style scoped>
.config-stack{display:grid;grid-template-columns:1fr 1fr;gap:.8rem;transition:opacity .15s}.config-stack.is-loading{opacity:.7}.config-panel{min-width:0;border:1px solid #dfe5ec;border-radius:8px;background:#fff;padding:.9rem}.config-panel>header{margin-bottom:.65rem}.config-panel header span{color:#738093;font-size:.61rem;font-weight:750}.config-panel h2{margin:.1rem 0 0;color:#273244;font-size:.92rem}.config-list{display:grid;border-top:1px solid #edf0f4}.config-list button{display:grid;grid-template-columns:26px minmax(0,1fr) auto 24px;align-items:center;gap:.55rem;min-height:54px;border:0;border-bottom:1px solid #edf0f4;background:#fff;text-align:left}.config-list button>i:first-child{color:#405189;font-size:1.1rem}.config-list strong,.config-list small{display:block}.config-list strong{color:#303b4d;font-size:.73rem}.config-list small{color:#8791a0;font-size:.61rem}.risk-swatch{width:13px;height:13px;border-radius:50%}.active-state{color:#25815f;font-size:.61rem;font-weight:700}.active-state.off{color:#8a94a3}.reason-grid{display:grid;grid-template-columns:1fr 1fr;gap:.4rem}.reason-grid>span{display:grid;grid-template-columns:18px 1fr auto;align-items:center;gap:.35rem;padding:.45rem .5rem;border:1px solid #e6eaf0;border-radius:5px;color:#445164;font-size:.66rem}.reason-grid b{color:#8792a2;font-size:.53rem;text-transform:uppercase}.financial-form{display:grid;grid-template-columns:repeat(4,1fr);gap:.55rem;align-items:end}.financial-form label span,.config-dialog label>span{display:block;margin-bottom:.25rem;color:#647184;font-size:.64rem;font-weight:650}.financial-form .wide{grid-column:span 2}.financial-form .form-control{font-size:.7rem}.financial-current{margin-top:.6rem;padding:.55rem;background:#f5f8fb;color:#5d697a;font-size:.65rem}.config-backdrop{position:fixed;z-index:1090;inset:0;display:grid;place-items:center;padding:1rem;background:rgba(24,32,45,.5)}.config-dialog{display:grid;gap:.7rem;width:min(560px,100%);max-height:90vh;overflow:auto;border-radius:8px;background:#fff;padding:1rem;box-shadow:0 24px 60px rgba(20,30,45,.24)}.config-dialog>header,.config-dialog>footer{display:flex;align-items:center;justify-content:space-between;gap:.5rem}.config-dialog h3{margin:0;color:#273244;font-size:1rem}.config-dialog>footer{justify-content:flex-end;padding-top:.65rem;border-top:1px solid #e8ecf1}.two-cols{display:grid;grid-template-columns:1fr 1fr;gap:.6rem}.check-line{display:flex;align-items:center;gap:.45rem;color:#526071;font-size:.7rem}.icon-btn{display:grid;place-items:center;width:32px;height:32px;border:1px solid #dbe1e9;border-radius:6px;background:#fff;color:#405189}@media(max-width:1000px){.config-stack{grid-template-columns:1fr}.financial-form{grid-template-columns:1fr 1fr}}@media(max-width:600px){.reason-grid,.financial-form,.two-cols{grid-template-columns:1fr}.financial-form .wide{grid-column:auto}}
</style>
