<script setup>
import { onMounted, reactive, ref } from 'vue'
import { useSocialWork } from '../../composables/useSocialWork'

const props = defineProps({ students: { type: Array, default: () => [] } })
const api = reactive(useSocialWork())
const rows = ref([])
const pagination = ref({ current_page: 1, last_page: 1, total: 0 })
const search = ref('')
const activeFilter = ref('1')
const modal = ref(false)
const editingId = ref(null)
const success = ref('')
const types = {
  orden_alejamiento: 'Orden de alejamiento', prohibicion_judicial: 'Prohibición judicial',
  restriccion_familiar: 'Restricción familiar', custodia_especial: 'Custodia o cuidado especial',
  persona_no_autorizada: 'Persona no autorizada', otra: 'Otra restricción',
}
const form = reactive({ student_profile_id: '', restricted_person_name: '', restricted_person_rut: '', restricted_person_relationship: '', restriction_type: 'persona_no_autorizada', reason: '', legal_reference: '', starts_on: new Date().toISOString().slice(0, 10), ends_on: '', active: true })
const name = student => student?.registered_name_resolved || student?.registered_name || [student?.first_name, student?.last_name].filter(Boolean).join(' ')
const date = value => value ? new Intl.DateTimeFormat('es-CL', { dateStyle: 'medium' }).format(new Date(value)) : 'Sin término'

async function load(page = 1) {
  const query = new URLSearchParams({ page, per_page: 20 })
  if (search.value) query.set('search', search.value)
  if (activeFilter.value !== '') query.set('active', activeFilter.value)
  try { const response = await api.get(`/pickup-restrictions?${query}`); rows.value = response.data || []; pagination.value = { current_page: response.current_page, last_page: response.last_page, total: response.total } } catch { rows.value = [] }
}
function reset() { editingId.value = null; Object.assign(form, { student_profile_id: '', restricted_person_name: '', restricted_person_rut: '', restricted_person_relationship: '', restriction_type: 'persona_no_autorizada', reason: '', legal_reference: '', starts_on: new Date().toISOString().slice(0, 10), ends_on: '', active: true }) }
function openNew() { reset(); modal.value = true }
function edit(item) { editingId.value = item.id; Object.assign(form, { student_profile_id: item.student_profile_id, restricted_person_name: item.restricted_person_name, restricted_person_rut: item.restricted_person_rut || '', restricted_person_relationship: item.restricted_person_relationship || '', restriction_type: item.restriction_type, reason: item.reason, legal_reference: item.legal_reference || '', starts_on: item.starts_on, ends_on: item.ends_on || '', active: Boolean(item.active) }); modal.value = true }
async function save() { const payload = { ...form, student_profile_id: Number(form.student_profile_id), ends_on: form.ends_on || null, active: Boolean(form.active) }; try { if (editingId.value) await api.put(`/pickup-restrictions/${editingId.value}`, payload); else await api.post('/pickup-restrictions', payload); success.value = editingId.value ? 'Restricción actualizada.' : 'Restricción de retiro creada.'; modal.value = false; await load(1) } catch {} }
async function finish(item) { if (!window.confirm(`¿Finalizar la restricción ${item.restriction_code}?`)) return; try { await api.remove(`/pickup-restrictions/${item.id}`); success.value = 'Restricción finalizada y conservada en el historial.'; await load(1) } catch {} }
onMounted(load)
</script>

<template>
  <section class="restriction-card"><header><div class="shield"><i class="bx bx-shield-quarter"></i></div><div><span>Resguardo de retiro</span><h2>Restricciones y personas no autorizadas</h2><p>Funcionalidad trasladada desde Inspectoría; su administración corresponde ahora a Trabajo Social.</p></div><button class="btn btn-danger ms-auto" @click="openNew"><i class="bx bx-plus"></i> Nueva restricción</button></header>
    <div v-if="success" class="alert alert-success mx-4 mt-3 mb-0">{{ success }}</div><div v-if="api.error" class="alert alert-danger mx-4 mt-3 mb-0">{{ api.error }}</div>
    <div class="filters"><div class="input-group"><span class="input-group-text"><i class="bx bx-search"></i></span><input v-model="search" class="form-control" placeholder="Buscar alumna, persona, RUT o motivo" @keyup.enter="load(1)"></div><select v-model="activeFilter" class="form-select" @change="load(1)"><option value="1">Solo vigentes</option><option value="0">Finalizadas</option><option value="">Todas</option></select><button class="btn btn-outline-primary" @click="load(1)">Buscar</button></div>
    <div class="notice"><i class="bx bx-lock-alt"></i><div><strong>Información de acceso restringido</strong><span>Estos antecedentes deben utilizarse únicamente para el resguardo de la alumna y el control institucional de retiros.</span></div></div>
    <div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Código</th><th>Alumna</th><th>Persona restringida</th><th>Tipo</th><th>Vigencia</th><th>Estado</th><th></th></tr></thead><tbody><tr v-for="item in rows" :key="item.id"><td><strong>{{ item.restriction_code }}</strong></td><td><strong>{{ name(item.student) }}</strong><small>{{ item.course_section?.display_name || item.student?.rut }}</small></td><td><strong>{{ item.restricted_person_name }}</strong><small>{{ item.restricted_person_rut || 'Sin RUT' }} · {{ item.restricted_person_relationship || 'Relación no informada' }}</small></td><td>{{ item.restriction_type_label }}</td><td>{{ date(item.starts_on) }} — {{ date(item.ends_on) }}</td><td><span class="state" :class="{ inactive: !item.active }">{{ item.active ? 'Vigente' : 'Finalizada' }}</span></td><td class="actions"><button class="btn btn-sm btn-outline-primary" @click="edit(item)">Editar</button><button v-if="item.active" class="btn btn-sm btn-outline-danger" @click="finish(item)">Finalizar</button></td></tr><tr v-if="!rows.length && !api.loading"><td colspan="7" class="empty">No hay restricciones para los filtros seleccionados.</td></tr></tbody></table></div>
    <div v-if="api.loading" class="loading"><span class="spinner-border spinner-border-sm"></span> Cargando restricciones autorizadas…</div><footer v-if="pagination.last_page > 1"><button class="btn btn-sm btn-light" :disabled="pagination.current_page <= 1" @click="load(pagination.current_page - 1)">Anterior</button><span>{{ pagination.current_page }} / {{ pagination.last_page }}</span><button class="btn btn-sm btn-light" :disabled="pagination.current_page >= pagination.last_page" @click="load(pagination.current_page + 1)">Siguiente</button></footer>
  </section>

  <Teleport to="body"><div v-if="modal" class="modal-overlay" @click.self="modal = false"><form class="modal-panel" @submit.prevent="save"><header><div><span>Resguardo institucional</span><h2>{{ editingId ? 'Editar restricción' : 'Nueva restricción de retiro' }}</h2></div><button type="button" @click="modal = false"><i class="bx bx-x"></i></button></header><div class="form-body"><label>Alumna *</label><select v-model="form.student_profile_id" class="form-select" :disabled="Boolean(editingId)" required><option value="">Selecciona</option><option v-for="student in students" :key="student.id" :value="student.id">{{ name(student) }} · {{ student.rut }}</option></select><div class="row"><div class="col-md-7"><label>Persona restringida *</label><input v-model="form.restricted_person_name" class="form-control" required></div><div class="col-md-5"><label>RUT</label><input v-model="form.restricted_person_rut" class="form-control"></div></div><div class="row"><div class="col-md-6"><label>Relación con alumna</label><input v-model="form.restricted_person_relationship" class="form-control"></div><div class="col-md-6"><label>Tipo de restricción *</label><select v-model="form.restriction_type" class="form-select"><option v-for="(typeLabel, typeValue) in types" :key="typeValue" :value="typeValue">{{ typeLabel }}</option></select></div></div><label>Motivo y antecedentes *</label><textarea v-model="form.reason" class="form-control" rows="4" required></textarea><label>Referencia legal o resolución</label><input v-model="form.legal_reference" class="form-control"><div class="row"><div class="col-md-6"><label>Inicio *</label><input v-model="form.starts_on" type="date" class="form-control" required></div><div class="col-md-6"><label>Término</label><input v-model="form.ends_on" type="date" class="form-control"></div></div></div><footer><button type="button" class="btn btn-light" @click="modal = false">Cancelar</button><button class="btn btn-danger" :disabled="api.loading">Guardar restricción</button></footer></form></div></Teleport>
</template>

<style scoped>
.restriction-card{background:#fff;border:1px solid #e4e7ed;border-radius:18px;box-shadow:0 18px 46px rgba(45,45,66,.08);overflow:hidden}.restriction-card>header{display:flex;align-items:center;gap:1rem;padding:1.35rem 1.5rem;background:linear-gradient(135deg,#fff5f6,#f7f3ff)}.shield{display:grid;place-items:center;width:48px;height:48px;border-radius:15px;background:#fff;color:#a13d50;font-size:1.5rem;box-shadow:0 8px 22px rgba(161,61,80,.12)}header span,.modal-panel header span{font-size:.67rem;text-transform:uppercase;letter-spacing:.11em;color:#9b4254;font-weight:800}.restriction-card h2,.modal-panel h2{font-size:1.2rem;color:#29364a;margin:.12rem 0}.restriction-card header p{margin:0;color:#748195}.filters{display:flex;gap:.65rem;padding:1rem 1.5rem}.filters .input-group{max-width:500px}.filters .form-select{max-width:180px}.notice{display:flex;gap:.65rem;align-items:center;margin:0 1.5rem 1rem;padding:.75rem .9rem;background:#fff8e7;border:1px solid #f0dfac;border-radius:12px;color:#755b22}.notice i{font-size:1.3rem}.notice strong,.notice span{display:block}.notice span{font-size:.75rem}thead th{font-size:.64rem;text-transform:uppercase;letter-spacing:.06em;color:#738095;padding:.75rem}tbody td{padding:.8rem}td strong,td small{display:block}td small{color:#84909e}.state{display:inline-block;padding:.27rem .52rem;background:#e5f8ef;color:#17704f;border-radius:999px;font-size:.7rem;font-weight:700}.state.inactive{background:#eef1f4;color:#7e8895}.actions{display:flex;gap:.35rem}.empty,.loading{text-align:center;padding:2rem;color:#748195}.restriction-card>footer{display:flex;justify-content:flex-end;gap:.7rem;padding:1rem}.modal-overlay{position:fixed;inset:0;z-index:1090;background:rgba(15,23,42,.6);backdrop-filter:blur(5px);display:grid;place-items:center;padding:1rem}.modal-panel{width:min(680px,96vw);max-height:94vh;overflow:auto;background:#fff;border-radius:20px;box-shadow:0 28px 80px rgba(15,23,42,.32)}.modal-panel>header{display:flex;justify-content:space-between;padding:1.15rem 1.35rem;border-bottom:1px solid #e8edf3}.modal-panel>header button{border:0;background:#f1f5f9;border-radius:50%;width:36px;height:36px;font-size:1.4rem}.form-body{padding:1.2rem 1.35rem}.form-body label{display:block;font-size:.74rem;font-weight:700;color:#526174;margin:.7rem 0 .3rem}.modal-panel>footer{display:flex;justify-content:flex-end;gap:.6rem;padding:1rem 1.35rem;border-top:1px solid #e8edf3}@media(max-width:800px){.restriction-card>header{align-items:flex-start;flex-wrap:wrap}.restriction-card>header .btn{margin-left:0!important}.filters{flex-wrap:wrap}.notice{margin-inline:.8rem}}
</style>
