<?php

namespace App\Services\Remuneration;

use App\Models\Cargo;
use App\Models\HumanResources\HrClimateActionPlan;
use App\Models\HumanResources\HrClimateSurvey;
use App\Models\HumanResources\HrCvBankEntry;
use App\Models\HumanResources\HrDocumentControl;
use App\Models\HumanResources\HrJobProfile;
use App\Models\HumanResources\HrLaborCertificate;
use App\Models\HumanResources\HrMedicalLeave;
use App\Models\HumanResources\HrOnboardingProcess;
use App\Models\HumanResources\HrReplacementPoolEntry;
use App\Models\HumanResources\HrWorkloadAssignment;
use App\Models\PermissionRequest;
use App\Models\Remuneration\RemunerationAccountingExport;
use App\Models\Remuneration\RemunerationAuditLog;
use App\Models\Remuneration\RemunerationConcept;
use App\Models\Remuneration\RemunerationContractSetting;
use App\Models\Remuneration\RemunerationEmployeeConcept;
use App\Models\Remuneration\RemunerationEmployeeProfile;
use App\Models\Remuneration\RemunerationLegalParameter;
use App\Models\Remuneration\RemunerationMovement;
use App\Models\Remuneration\RemunerationPayment;
use App\Models\Remuneration\RemunerationPayroll;
use App\Models\Remuneration\RemunerationPeriod;
use App\Models\Staff;
use Illuminate\Validation\Rule;

class RemunerationResourceRegistry
{
    /**
     * @return array<string, array<string, mixed>>
     */
    public function all(): array
    {
        return [
            'periods' => [
                'model' => RemunerationPeriod::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::CLOSE_PERIOD_PERMISSION,
                'search' => ['name', 'status'],
                'filters' => ['year', 'month', 'status'],
                'order_by' => 'year',
                'order_direction' => 'desc',
                'rules' => fn (?int $id) => [
                    'year' => ['required', 'integer', 'min:2020', 'max:2100'],
                    'month' => ['required', 'integer', 'min:1', 'max:12'],
                    'name' => ['required', 'string', 'max:191'],
                    'status' => ['nullable', 'string', 'max:40'],
                    'period_start' => ['required', 'date'],
                    'period_end' => ['required', 'date', 'after_or_equal:period_start'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'parameters' => [
                'model' => RemunerationLegalParameter::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::PARAMETERS_PERMISSION,
                'search' => ['code', 'name', 'category', 'source_reference'],
                'filters' => ['code', 'category', 'unit', 'is_active'],
                'order_by' => 'code',
                'rules' => fn (?int $id) => [
                    'code' => ['required', 'string', 'max:80'],
                    'name' => ['required', 'string', 'max:191'],
                    'category' => ['required', 'string', 'max:80'],
                    'value' => ['required', 'numeric'],
                    'unit' => ['required', 'string', 'max:30'],
                    'effective_from' => ['required', 'date'],
                    'effective_until' => ['nullable', 'date', 'after_or_equal:effective_from'],
                    'source_reference' => ['nullable', 'string', 'max:191'],
                    'metadata' => ['nullable', 'array'],
                    'is_active' => ['nullable', 'boolean'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'profiles' => [
                'model' => RemunerationEmployeeProfile::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::EMPLOYEES_PERMISSION,
                'search' => ['bank_name', 'afp_name', 'health_institution_name'],
                'filters' => ['staff_id', 'payment_method', 'afp_name', 'is_active'],
                'order_by' => 'id',
                'with' => ['staff:id,full_name,rut,cargo_id'],
                'rules' => fn (?int $id) => [
                    'staff_id' => ['required', 'integer', 'exists:staff,id', Rule::unique('remuneration_employee_profiles', 'staff_id')->ignore($id)],
                    'payment_method' => ['nullable', 'string', 'max:60'],
                    'bank_name' => ['nullable', 'string', 'max:191'],
                    'bank_account_type' => ['nullable', 'string', 'max:80'],
                    'bank_account_number' => ['nullable', 'string', 'max:191'],
                    'afp_name' => ['nullable', 'string', 'max:191'],
                    'afp_rate' => ['nullable', 'numeric', 'min:0'],
                    'is_pensioned' => ['nullable', 'boolean'],
                    'health_institution_type' => ['nullable', 'string', 'max:40'],
                    'health_institution_name' => ['nullable', 'string', 'max:191'],
                    'health_plan_amount' => ['nullable', 'numeric', 'min:0'],
                    'health_plan_unit' => ['nullable', 'string', 'max:30'],
                    'has_afc' => ['nullable', 'boolean'],
                    'afc_started_at' => ['nullable', 'date'],
                    'family_allowance_tramo' => ['nullable', 'string', 'max:20'],
                    'apv_institution' => ['nullable', 'string', 'max:191'],
                    'apv_amount' => ['nullable', 'numeric', 'min:0'],
                    'apv_unit' => ['nullable', 'string', 'max:30'],
                    'tax_regime' => ['nullable', 'string', 'max:60'],
                    'family_dependents' => ['nullable', 'array'],
                    'is_active' => ['nullable', 'boolean'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'contract-settings' => [
                'model' => RemunerationContractSetting::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::CONTRACTS_PERMISSION,
                'search' => ['employee_type', 'teacher_level'],
                'filters' => ['staff_id', 'contract_id', 'employee_type', 'teacher_career', 'is_active'],
                'order_by' => 'id',
                'with' => ['staff:id,full_name,rut', 'contract:id,staff_id,position_name,start_date,end_date,status'],
                'rules' => fn (?int $id) => [
                    'staff_id' => ['required', 'integer', 'exists:staff,id'],
                    'contract_id' => ['nullable', 'integer', 'exists:contracts,id', Rule::unique('remuneration_contract_settings', 'contract_id')->ignore($id)],
                    'employee_profile_id' => ['nullable', 'integer', 'exists:remuneration_employee_profiles,id'],
                    'employee_type' => ['required', 'string', 'max:80'],
                    'teacher_career' => ['nullable', 'boolean'],
                    'teacher_level' => ['nullable', 'string', 'max:80'],
                    'bienios' => ['nullable', 'integer', 'min:0', 'max:99'],
                    'priority_percent' => ['nullable', 'numeric', 'min:0'],
                    'base_salary' => ['required', 'integer', 'min:0'],
                    'weekly_hours' => ['required', 'numeric', 'min:0'],
                    'basic_hours' => ['nullable', 'numeric', 'min:0'],
                    'middle_hours' => ['nullable', 'numeric', 'min:0'],
                    'pie_hours' => ['nullable', 'numeric', 'min:0'],
                    'sep_hours' => ['nullable', 'numeric', 'min:0'],
                    'pro_retention_hours' => ['nullable', 'numeric', 'min:0'],
                    'funding_distribution' => ['nullable', 'array'],
                    'accounting_debit_account_id' => ['nullable', 'integer', 'exists:accounting_manual_accounts,id'],
                    'accounting_credit_account_id' => ['nullable', 'integer', 'exists:accounting_manual_accounts,id'],
                    'is_active' => ['nullable', 'boolean'],
                    'effective_from' => ['nullable', 'date'],
                    'effective_until' => ['nullable', 'date', 'after_or_equal:effective_from'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'concepts' => [
                'model' => RemunerationConcept::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::CONCEPTS_PERMISSION,
                'search' => ['code', 'name', 'description'],
                'filters' => ['type', 'is_legal', 'is_system', 'is_active'],
                'order_by' => 'sort_order',
                'rules' => fn (?int $id) => [
                    'code' => ['required', 'string', 'max:80', Rule::unique('remuneration_concepts', 'code')->ignore($id)],
                    'name' => ['required', 'string', 'max:191'],
                    'type' => ['required', 'string', 'max:40'],
                    'is_taxable' => ['nullable', 'boolean'],
                    'is_imponible' => ['nullable', 'boolean'],
                    'affects_tax_base' => ['nullable', 'boolean'],
                    'affects_net' => ['nullable', 'boolean'],
                    'is_legal' => ['nullable', 'boolean'],
                    'is_system' => ['nullable', 'boolean'],
                    'calculation_type' => ['required', 'string', 'max:40'],
                    'amount' => ['nullable', 'integer'],
                    'default_unit' => ['nullable', 'string', 'max:30'],
                    'formula' => ['nullable', 'string'],
                    'accounting_debit_account_id' => ['nullable', 'integer', 'exists:accounting_manual_accounts,id'],
                    'accounting_credit_account_id' => ['nullable', 'integer', 'exists:accounting_manual_accounts,id'],
                    'sort_order' => ['nullable', 'integer', 'min:0'],
                    'is_active' => ['nullable', 'boolean'],
                    'description' => ['nullable', 'string'],
                ],
            ],
            'employee-concepts' => [
                'model' => RemunerationEmployeeConcept::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::CONCEPTS_PERMISSION,
                'filters' => ['staff_id', 'contract_id', 'concept_id', 'is_active'],
                'order_by' => 'id',
                'with' => ['staff:id,full_name,rut', 'concept:id,code,name,type'],
                'rules' => fn (?int $id) => [
                    'staff_id' => ['required', 'integer', 'exists:staff,id'],
                    'contract_id' => ['nullable', 'integer', 'exists:contracts,id'],
                    'concept_id' => ['required', 'integer', 'exists:remuneration_concepts,id'],
                    'is_recurring' => ['nullable', 'boolean'],
                    'amount' => ['nullable', 'integer'],
                    'formula_override' => ['nullable', 'string'],
                    'starts_at' => ['nullable', 'date'],
                    'ends_at' => ['nullable', 'date', 'after_or_equal:starts_at'],
                    'is_active' => ['nullable', 'boolean'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'movements' => [
                'model' => RemunerationMovement::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::MOVEMENTS_PERMISSION,
                'search' => ['description', 'movement_type', 'status'],
                'filters' => ['period_id', 'staff_id', 'movement_type', 'status', 'funding_source_id', 'cost_center_id'],
                'order_by' => 'id',
                'order_direction' => 'desc',
                'with' => ['period:id,name,year,month,status', 'staff:id,full_name,rut', 'concept:id,code,name,type', 'fundingSource:id,name', 'costCenter:id,name'],
                'rules' => fn (?int $id) => [
                    'period_id' => ['required', 'integer', 'exists:remuneration_periods,id'],
                    'staff_id' => ['required', 'integer', 'exists:staff,id'],
                    'contract_id' => ['nullable', 'integer', 'exists:contracts,id'],
                    'concept_id' => ['nullable', 'integer', 'exists:remuneration_concepts,id'],
                    'movement_type' => ['required', 'string', 'max:60'],
                    'source_type' => ['nullable', 'string', 'max:60'],
                    'description' => ['required', 'string', 'max:191'],
                    'amount' => ['nullable', 'integer', 'min:0'],
                    'quantity' => ['nullable', 'numeric'],
                    'unit_value' => ['nullable', 'integer'],
                    'affects_days' => ['nullable', 'numeric', 'min:0'],
                    'starts_at' => ['nullable', 'date'],
                    'ends_at' => ['nullable', 'date', 'after_or_equal:starts_at'],
                    'status' => ['nullable', 'string', 'max:40'],
                    'funding_source_id' => ['nullable', 'integer', 'exists:accounting_funding_sources,id'],
                    'cost_center_id' => ['nullable', 'integer', 'exists:accounting_cost_centers,id'],
                    'metadata' => ['nullable', 'array'],
                ],
            ],
            'payrolls' => [
                'model' => RemunerationPayroll::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::CALCULATE_PERMISSION,
                'search' => ['code', 'status', 'payroll_type'],
                'filters' => ['period_id', 'staff_id', 'status', 'payroll_type'],
                'order_by' => 'id',
                'order_direction' => 'desc',
                'with' => ['period:id,name,year,month,status', 'staff:id,full_name,rut,cargo_id', 'contract:id,position_name', 'lines', 'distributions.fundingSource:id,name', 'distributions.costCenter:id,name', 'payments'],
                'rules' => fn (?int $id) => [
                    'observations' => ['nullable', 'string'],
                    'status' => ['nullable', 'string', 'max:40'],
                ],
            ],
            'payments' => [
                'model' => RemunerationPayment::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::PAYMENTS_PERMISSION,
                'search' => ['reference', 'payment_method', 'status'],
                'filters' => ['payroll_id', 'payment_method', 'status'],
                'order_by' => 'payment_date',
                'order_direction' => 'desc',
                'with' => ['payroll:id,code,staff_id,period_id,net_amount,status', 'payroll.staff:id,full_name,rut'],
                'rules' => fn (?int $id) => [
                    'payroll_id' => ['required', 'integer', 'exists:remuneration_payrolls,id'],
                    'payment_date' => ['required', 'date'],
                    'amount' => ['required', 'integer', 'min:1'],
                    'payment_method' => ['required', 'string', 'max:60'],
                    'bank_account_id' => ['nullable', 'integer', 'exists:accounting_bank_accounts,id'],
                    'reference' => ['nullable', 'string', 'max:191'],
                    'status' => ['nullable', 'string', 'max:40'],
                    'metadata' => ['nullable', 'array'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'accounting-exports' => [
                'model' => RemunerationAccountingExport::class,
                'view_permission' => RemunerationAccessService::ACCOUNTING_PERMISSION,
                'manage_permission' => RemunerationAccessService::ACCOUNTING_PERMISSION,
                'search' => ['export_code', 'status'],
                'filters' => ['period_id', 'payroll_id', 'status'],
                'order_by' => 'id',
                'order_direction' => 'desc',
                'with' => ['period:id,name,year,month', 'payroll:id,code,staff_id,total_cost', 'journalEntry:id,entry_number,status'],
                'rules' => fn (?int $id) => [],
            ],
            'medical-leaves' => [
                'model' => HrMedicalLeave::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::HR_MANAGEMENT_PERMISSION,
                'search' => ['license_number', 'issuer', 'diagnosis_group', 'status'],
                'filters' => ['staff_id', 'period_id', 'status', 'affects_payroll'],
                'order_by' => 'starts_at',
                'order_direction' => 'desc',
                'with' => ['staff:id,full_name,rut', 'period:id,name,year,month', 'documentControl:id,title,status', 'payrollMovement:id,description,status'],
                'rules' => fn (?int $id) => [
                    'staff_id' => ['required', 'integer', 'exists:staff,id'],
                    'period_id' => ['nullable', 'integer', 'exists:remuneration_periods,id'],
                    'document_control_id' => ['nullable', 'integer', 'exists:hr_document_controls,id'],
                    'payroll_movement_id' => ['nullable', 'integer', 'exists:remuneration_movements,id'],
                    'license_number' => ['nullable', 'string', 'max:120'],
                    'issuer' => ['nullable', 'string', 'max:160'],
                    'diagnosis_group' => ['nullable', 'string', 'max:160'],
                    'starts_at' => ['required', 'date'],
                    'ends_at' => ['required', 'date', 'after_or_equal:starts_at'],
                    'days' => ['required', 'numeric', 'min:0'],
                    'affects_payroll' => ['nullable', 'boolean'],
                    'subsidy_status' => ['nullable', 'string', 'max:60'],
                    'status' => ['nullable', 'string', 'max:40'],
                    'metadata' => ['nullable', 'array'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'birthdays' => [
                'model' => Staff::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::EMPLOYEES_PERMISSION,
                'search' => ['full_name', 'rut', 'institutional_email'],
                'filters' => ['status', 'active'],
                'order_by' => 'birth_date',
                'with' => ['cargo:id,name'],
                'read_only' => true,
                'rules' => fn (?int $id) => [],
            ],
            'permissions' => [
                'model' => PermissionRequest::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::HR_MANAGEMENT_PERMISSION,
                'search' => ['reason', 'status', 'attendance_status', 'payroll_status'],
                'filters' => ['staff_id', 'permission_type_id', 'status', 'payroll_status', 'affects_salary'],
                'order_by' => 'start_date',
                'order_direction' => 'desc',
                'with' => ['staff:id,full_name,rut', 'permissionType:id,name,slug'],
                'rules' => fn (?int $id) => [
                    'staff_id' => ['required', 'integer', 'exists:staff,id'],
                    'permission_type_id' => ['required', 'integer', 'exists:permission_types,id'],
                    'start_date' => ['required', 'date'],
                    'end_date' => ['required', 'date', 'after_or_equal:start_date'],
                    'start_time' => ['nullable', 'date_format:H:i'],
                    'end_time' => ['nullable', 'date_format:H:i'],
                    'duration_hours' => ['nullable', 'numeric', 'min:0'],
                    'duration_days' => ['nullable', 'numeric', 'min:0'],
                    'duration_label' => ['nullable', 'string', 'max:191'],
                    'is_full_day' => ['nullable', 'boolean'],
                    'is_half_day' => ['nullable', 'boolean'],
                    'with_pay' => ['nullable', 'boolean'],
                    'affects_salary' => ['nullable', 'boolean'],
                    'affects_attendance' => ['nullable', 'boolean'],
                    'requires_replacement' => ['nullable', 'boolean'],
                    'reason' => ['required', 'string', 'max:191'],
                    'description' => ['nullable', 'string'],
                    'status' => ['nullable', 'string', 'max:60'],
                    'attendance_status' => ['nullable', 'string', 'max:60'],
                    'payroll_status' => ['nullable', 'string', 'max:60'],
                    'salary_discount_hours' => ['nullable', 'numeric', 'min:0'],
                    'salary_discount_days' => ['nullable', 'numeric', 'min:0'],
                    'requires_regularization' => ['nullable', 'boolean'],
                    'internal_observations' => ['nullable', 'string'],
                ],
            ],
            'staff-management' => [
                'model' => Staff::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::EMPLOYEES_PERMISSION,
                'search' => ['full_name', 'rut', 'institutional_email', 'personal_email', 'status'],
                'filters' => ['cargo_id', 'contract_type', 'status', 'active'],
                'order_by' => 'full_name',
                'with' => ['cargo:id,name'],
                'rules' => fn (?int $id) => [
                    'full_name' => ['required', 'string', 'max:191'],
                    'rut' => ['required', 'string', 'max:20', Rule::unique('staff', 'rut')->ignore($id)],
                    'birth_date' => ['nullable', 'date'],
                    'institutional_email' => ['nullable', 'email', 'max:191', Rule::unique('staff', 'institutional_email')->ignore($id)],
                    'personal_email' => ['nullable', 'email', 'max:191'],
                    'phone' => ['nullable', 'string', 'max:50'],
                    'address' => ['nullable', 'string', 'max:191'],
                    'cargo_id' => ['nullable', 'integer', 'exists:cargos,id'],
                    'contract_type' => ['nullable', 'string', 'max:100'],
                    'start_date' => ['nullable', 'date'],
                    'end_date' => ['nullable', 'date', 'after_or_equal:start_date'],
                    'status' => ['nullable', 'string', 'max:50'],
                    'workday' => ['nullable', 'string', 'max:100'],
                    'contract_hours' => ['nullable', 'numeric', 'min:0'],
                    'professional_title' => ['nullable', 'string', 'max:191'],
                    'specialty' => ['nullable', 'string', 'max:191'],
                    'active' => ['nullable', 'boolean'],
                    'internal_notes' => ['nullable', 'string'],
                ],
            ],
            'document-controls' => [
                'model' => HrDocumentControl::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::HR_MANAGEMENT_PERMISSION,
                'search' => ['title', 'document_type', 'folio', 'status', 'owner_area'],
                'filters' => ['staff_id', 'document_type', 'status', 'related_area'],
                'order_by' => 'expires_at',
                'order_direction' => 'asc',
                'with' => ['staff:id,full_name,rut'],
                'rules' => fn (?int $id) => [
                    'staff_id' => ['nullable', 'integer', 'exists:staff,id'],
                    'related_area' => ['nullable', 'string', 'max:80'],
                    'document_type' => ['required', 'string', 'max:100'],
                    'title' => ['required', 'string', 'max:191'],
                    'folio' => ['nullable', 'string', 'max:120'],
                    'issued_at' => ['nullable', 'date'],
                    'expires_at' => ['nullable', 'date', 'after_or_equal:issued_at'],
                    'alert_days' => ['nullable', 'integer', 'min:0', 'max:365'],
                    'status' => ['nullable', 'string', 'max:40'],
                    'owner_area' => ['nullable', 'string', 'max:120'],
                    'file_path' => ['nullable', 'string', 'max:191'],
                    'metadata' => ['nullable', 'array'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'onboarding' => [
                'model' => HrOnboardingProcess::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::HR_MANAGEMENT_PERMISSION,
                'search' => ['status', 'notes'],
                'filters' => ['staff_id', 'job_profile_id', 'responsible_user_id', 'status'],
                'order_by' => 'starts_at',
                'order_direction' => 'desc',
                'with' => ['staff:id,full_name,rut', 'jobProfile:id,title,code', 'responsibleUser:id,name'],
                'rules' => fn (?int $id) => [
                    'staff_id' => ['required', 'integer', 'exists:staff,id'],
                    'job_profile_id' => ['nullable', 'integer', 'exists:hr_job_profiles,id'],
                    'responsible_user_id' => ['nullable', 'integer', 'exists:users,id'],
                    'starts_at' => ['required', 'date'],
                    'target_completion_at' => ['nullable', 'date', 'after_or_equal:starts_at'],
                    'completed_at' => ['nullable', 'date'],
                    'status' => ['nullable', 'string', 'max:40'],
                    'documents_checklist' => ['nullable', 'array'],
                    'trainings_checklist' => ['nullable', 'array'],
                    'accesses_checklist' => ['nullable', 'array'],
                    'materials_checklist' => ['nullable', 'array'],
                    'completion_percent' => ['nullable', 'numeric', 'min:0', 'max:100'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'climate-surveys' => [
                'model' => HrClimateSurvey::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::HR_MANAGEMENT_PERMISSION,
                'search' => ['title', 'scope', 'status', 'risk_level'],
                'filters' => ['status', 'risk_level', 'scope'],
                'order_by' => 'starts_at',
                'order_direction' => 'desc',
                'with' => ['actionPlans:id,survey_id,title,status,due_date,risk_level'],
                'rules' => fn (?int $id) => [
                    'title' => ['required', 'string', 'max:191'],
                    'scope' => ['nullable', 'string', 'max:140'],
                    'starts_at' => ['nullable', 'date'],
                    'ends_at' => ['nullable', 'date', 'after_or_equal:starts_at'],
                    'status' => ['nullable', 'string', 'max:40'],
                    'response_count' => ['nullable', 'integer', 'min:0'],
                    'satisfaction_score' => ['nullable', 'numeric', 'min:0', 'max:100'],
                    'risk_level' => ['nullable', 'string', 'max:40'],
                    'questions' => ['nullable', 'array'],
                    'alerts' => ['nullable', 'array'],
                    'report_payload' => ['nullable', 'array'],
                    'summary' => ['nullable', 'string'],
                ],
            ],
            'climate-action-plans' => [
                'model' => HrClimateActionPlan::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::HR_MANAGEMENT_PERMISSION,
                'search' => ['title', 'risk_level', 'status', 'action'],
                'filters' => ['survey_id', 'owner_user_id', 'status', 'risk_level'],
                'order_by' => 'due_date',
                'with' => ['survey:id,title,scope', 'ownerUser:id,name'],
                'rules' => fn (?int $id) => [
                    'survey_id' => ['nullable', 'integer', 'exists:hr_climate_surveys,id'],
                    'owner_user_id' => ['nullable', 'integer', 'exists:users,id'],
                    'title' => ['required', 'string', 'max:191'],
                    'risk_level' => ['nullable', 'string', 'max:40'],
                    'action' => ['nullable', 'string'],
                    'due_date' => ['nullable', 'date'],
                    'completed_at' => ['nullable', 'date'],
                    'status' => ['nullable', 'string', 'max:40'],
                    'evidence' => ['nullable', 'array'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'workload' => [
                'model' => HrWorkloadAssignment::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::HR_MANAGEMENT_PERMISSION,
                'search' => ['function_name', 'role_type', 'status'],
                'filters' => ['staff_id', 'contract_id', 'period_id', 'department_id', 'status'],
                'order_by' => 'id',
                'order_direction' => 'desc',
                'with' => ['staff:id,full_name,rut', 'contract:id,position_name,start_date,end_date,status', 'period:id,name,year,month', 'department:id,name', 'replacementStaff:id,full_name,rut'],
                'rules' => fn (?int $id) => [
                    'staff_id' => ['required', 'integer', 'exists:staff,id'],
                    'contract_id' => ['nullable', 'integer', 'exists:contracts,id'],
                    'period_id' => ['nullable', 'integer', 'exists:remuneration_periods,id'],
                    'department_id' => ['nullable', 'integer', 'exists:departments,id'],
                    'replacement_staff_id' => ['nullable', 'integer', 'exists:staff,id'],
                    'function_name' => ['required', 'string', 'max:191'],
                    'role_type' => ['nullable', 'string', 'max:80'],
                    'contracted_hours' => ['nullable', 'numeric', 'min:0'],
                    'classroom_hours' => ['nullable', 'numeric', 'min:0'],
                    'non_classroom_hours' => ['nullable', 'numeric', 'min:0'],
                    'coordination_hours' => ['nullable', 'numeric', 'min:0'],
                    'pie_hours' => ['nullable', 'numeric', 'min:0'],
                    'sep_hours' => ['nullable', 'numeric', 'min:0'],
                    'replacement_hours' => ['nullable', 'numeric', 'min:0'],
                    'starts_at' => ['nullable', 'date'],
                    'ends_at' => ['nullable', 'date', 'after_or_equal:starts_at'],
                    'status' => ['nullable', 'string', 'max:40'],
                    'metadata' => ['nullable', 'array'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'cv-bank' => [
                'model' => HrCvBankEntry::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::HR_MANAGEMENT_PERMISSION,
                'search' => ['full_name', 'rut', 'email', 'desired_position', 'specialty', 'status'],
                'filters' => ['desired_position', 'specialty', 'status', 'rating'],
                'order_by' => 'id',
                'order_direction' => 'desc',
                'rules' => fn (?int $id) => [
                    'full_name' => ['required', 'string', 'max:191'],
                    'rut' => ['nullable', 'string', 'max:20'],
                    'email' => ['nullable', 'email', 'max:191'],
                    'phone' => ['nullable', 'string', 'max:80'],
                    'source' => ['nullable', 'string', 'max:120'],
                    'desired_position' => ['nullable', 'string', 'max:160'],
                    'specialty' => ['nullable', 'string', 'max:160'],
                    'experience_years' => ['nullable', 'numeric', 'min:0'],
                    'availability' => ['nullable', 'string', 'max:120'],
                    'rating' => ['nullable', 'integer', 'min:1', 'max:5'],
                    'status' => ['nullable', 'string', 'max:40'],
                    'cv_path' => ['nullable', 'string', 'max:191'],
                    'metadata' => ['nullable', 'array'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'replacement-pool' => [
                'model' => HrReplacementPoolEntry::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::HR_MANAGEMENT_PERMISSION,
                'search' => ['full_name', 'specialty', 'subject_area', 'status'],
                'filters' => ['cv_bank_entry_id', 'staff_id', 'specialty', 'subject_area', 'status', 'rating'],
                'order_by' => 'rating',
                'order_direction' => 'desc',
                'with' => ['cvBankEntry:id,full_name,desired_position,specialty', 'staff:id,full_name,rut'],
                'rules' => fn (?int $id) => [
                    'cv_bank_entry_id' => ['nullable', 'integer', 'exists:hr_cv_bank_entries,id'],
                    'staff_id' => ['nullable', 'integer', 'exists:staff,id'],
                    'full_name' => ['required', 'string', 'max:191'],
                    'specialty' => ['nullable', 'string', 'max:160'],
                    'subject_area' => ['nullable', 'string', 'max:160'],
                    'available_from' => ['nullable', 'date'],
                    'available_until' => ['nullable', 'date', 'after_or_equal:available_from'],
                    'preferred_hours' => ['nullable', 'numeric', 'min:0'],
                    'rating' => ['nullable', 'integer', 'min:1', 'max:5'],
                    'last_replacement_at' => ['nullable', 'date'],
                    'status' => ['nullable', 'string', 'max:40'],
                    'metadata' => ['nullable', 'array'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'job-profiles' => [
                'model' => HrJobProfile::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::HR_MANAGEMENT_PERMISSION,
                'search' => ['code', 'title', 'area', 'status'],
                'filters' => ['cargo_id', 'area', 'status'],
                'order_by' => 'title',
                'with' => ['cargo:id,name'],
                'rules' => fn (?int $id) => [
                    'cargo_id' => ['nullable', 'integer', 'exists:cargos,id'],
                    'code' => ['required', 'string', 'max:80', Rule::unique('hr_job_profiles', 'code')->ignore($id)],
                    'title' => ['required', 'string', 'max:191'],
                    'area' => ['nullable', 'string', 'max:140'],
                    'purpose' => ['nullable', 'string'],
                    'responsibilities' => ['nullable', 'array'],
                    'requirements' => ['nullable', 'array'],
                    'competencies' => ['nullable', 'array'],
                    'workload_profile' => ['nullable', 'array'],
                    'version' => ['nullable', 'string', 'max:40'],
                    'status' => ['nullable', 'string', 'max:40'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'labor-certificates' => [
                'model' => HrLaborCertificate::class,
                'view_permission' => RemunerationAccessService::VIEW_PERMISSION,
                'manage_permission' => RemunerationAccessService::HR_MANAGEMENT_PERMISSION,
                'search' => ['certificate_type', 'purpose', 'folio', 'status'],
                'filters' => ['staff_id', 'certificate_type', 'status', 'signed_by_user_id'],
                'order_by' => 'issued_at',
                'order_direction' => 'desc',
                'with' => ['staff:id,full_name,rut,start_date,contract_type,contract_hours,cargo_id', 'staff.cargo:id,name', 'signedByUser:id,name'],
                'rules' => fn (?int $id) => [
                    'staff_id' => ['required', 'integer', 'exists:staff,id'],
                    'certificate_type' => ['required', 'string', 'max:100'],
                    'purpose' => ['nullable', 'string', 'max:180'],
                    'requested_at' => ['nullable', 'date'],
                    'issued_at' => ['nullable', 'date'],
                    'folio' => ['nullable', 'string', 'max:120', Rule::unique('hr_labor_certificates', 'folio')->ignore($id)],
                    'signed_by_user_id' => ['nullable', 'integer', 'exists:users,id'],
                    'status' => ['nullable', 'string', 'max:40'],
                    'payload' => ['nullable', 'array'],
                    'notes' => ['nullable', 'string'],
                ],
            ],
            'audit-logs' => [
                'model' => RemunerationAuditLog::class,
                'view_permission' => RemunerationAccessService::ADMIN_PERMISSION,
                'manage_permission' => RemunerationAccessService::ADMIN_PERMISSION,
                'search' => ['action', 'module', 'reason'],
                'filters' => ['user_id', 'action', 'auditable_type', 'auditable_id'],
                'order_by' => 'id',
                'order_direction' => 'desc',
                'with' => ['user:id,name,email'],
                'rules' => fn (?int $id) => [],
            ],
        ];
    }

    /**
     * @return array<string, mixed>
     */
    public function get(string $resource): array
    {
        $resources = $this->all();
        abort_unless(isset($resources[$resource]), 404, 'Recurso de remuneraciones no encontrado.');

        return $resources[$resource];
    }
}
