<script setup>
import { computed, onBeforeUnmount, reactive, ref, watch } from "vue";
import Swal from "sweetalert2";
import { libroDigitalApi } from "../../../services/libro-digital/api";
import LibroDigitalStatePanel from "../LibroDigitalStatePanel.vue";
import LibroDigitalStatusBadge from "../LibroDigitalStatusBadge.vue";
import { confirmAction, errorMessage, formatDate, payloadItems, showError, showSuccess, studentLabel } from "../module-utils";

const props = defineProps({ type: { type: String, required: true }, bookId: { type: [Number, String], required: true }, context: { type: Object, required: true }, roster: { type: Array, default: () => [] }, canManage: { type: Boolean, default: false } });
const loading = ref(false); const error = ref(null); const items = ref([]); const showForm = ref(false); const saving = ref(false); const selectedStudentId = ref(null); let controller = null;
const form = reactive({ student_profile_id: null, occurred_on: "", title: "", category: "", description: "", actions: "", status: "open", confidentiality_level: "reserved", professional_staff_id: null });
const definitions = {
  pie: { eyebrow: "APOYO A LA INCLUSIÓN", title: "PIE y trabajo colaborativo", description: "Registros autorizados de apoyo, coordinación y seguimiento PIE.", add: "Nuevo registro PIE", empty: "No hay actividades PIE en el libro." },
  coexistence: { eyebrow: "CONVIVENCIA ESCOLAR", title: "Anotaciones y convivencia", description: "Registros por estudiante con nivel de reserva y acceso funcional.", add: "Nueva anotación", empty: "Selecciona una estudiante o crea su primera anotación." },
  absences: { eyebrow: "TRAYECTORIA EDUCATIVA", title: "Ausencias prolongadas", description: "Casos, acciones de contacto y seguimiento de continuidad escolar.", add: "Nuevo caso", empty: "No hay casos de ausencia prolongada para este libro." },
  parvularia: { eyebrow: "LIBRO TÉCNICO PEDAGÓGICO", title: "Parvularia", description: "Planificación, experiencias de aprendizaje y evaluación del grupo.", add: "Nueva planificación", empty: "No hay planificaciones registradas para este libro." },
};
const definition = computed(() => definitions[props.type]);
const students = computed(() => props.roster.map((row) => row.student || row).filter((student) => student?.id));

const resetForm = () => Object.assign(form, { student_profile_id: selectedStudentId.value, occurred_on: new Date().toISOString().slice(0, 10), title: "", category: props.type === "pie" ? "collaborative_work" : props.type === "parvularia" ? "learning_experience" : "", description: "", actions: "", status: "open", confidentiality_level: props.type === "coexistence" ? "restricted" : "reserved", professional_staff_id: null });
const load = async () => { controller?.abort(); controller = new AbortController(); loading.value = true; error.value = null; try { let response; if (props.type === "pie") response = await libroDigitalApi.pieRecords(props.bookId, { per_page: 200 }, controller.signal); if (props.type === "coexistence") { if (!selectedStudentId.value) { items.value = []; return; } response = await libroDigitalApi.coexistence(selectedStudentId.value, { academic_year_id: props.context.academic_year_id, per_page: 200 }, controller.signal); } if (props.type === "absences") response = await libroDigitalApi.absenceCases({ book_id: props.bookId, course_section_id: props.context.course_section_id, academic_year_id: props.context.academic_year_id, per_page: 200 }, controller.signal); if (props.type === "parvularia") response = await libroDigitalApi.parvulariaPlanning(props.bookId, { per_page: 200 }, controller.signal); items.value = payloadItems(response); } catch (requestError) { if (requestError?.code !== "ERR_CANCELED") error.value = requestError; } finally { loading.value = false; } };
watch([() => props.type, () => props.bookId, selectedStudentId], load, { immediate: true }); onBeforeUnmount(() => controller?.abort());
const openCreate = () => { if (!props.canManage) return; resetForm(); showForm.value = true; };
const save = async () => { saving.value = true; try { const payload = { ...form, book_id: props.bookId, academic_year_id: props.context.academic_year_id, course_section_id: props.context.course_section_id }; if (props.type === "pie") await libroDigitalApi.createPieRecord(props.bookId, payload); if (props.type === "coexistence") { const studentId = form.student_profile_id || selectedStudentId.value; if (!studentId) throw new Error("Selecciona una estudiante."); await libroDigitalApi.createCoexistence(studentId, payload); selectedStudentId.value = studentId; } if (props.type === "absences") await libroDigitalApi.createAbsenceCase(payload); if (props.type === "parvularia") await libroDigitalApi.createParvulariaPlanning(props.bookId, payload); showForm.value = false; await load(); await showSuccess("Registro guardado"); } catch (requestError) { await showError(requestError); } finally { saving.value = false; } };
const resolve = async (item) => { const result = await Swal.fire({ title: "Resolver caso", input: "textarea", inputLabel: "Resultado y fundamento", showCancelButton: true, confirmButtonText: "Resolver", inputValidator: (value) => !value?.trim() ? "Ingresa el resultado." : undefined }); if (!result.isConfirmed) return; try { await libroDigitalApi.resolveAbsenceCase(item, { resolution: result.value.trim() }); await load(); } catch (requestError) { await showError(requestError); } };
const addAction = async (item) => { const result = await Swal.fire({ title: "Registrar acción", input: "textarea", inputLabel: "Contacto, gestión o antecedente", showCancelButton: true, confirmButtonText: "Guardar", inputValidator: (value) => !value?.trim() ? "Describe la acción." : undefined }); if (!result.isConfirmed) return; try { await libroDigitalApi.addAbsenceAction(item, { description: result.value.trim(), occurred_at: new Date().toISOString() }); await load(); } catch (requestError) { await showError(requestError); } };
</script>

<template>
  <section class="lcd-operational" :aria-labelledby="`lcd-${type}-title`" :aria-busy="loading || saving">
    <header><div><span>{{ definition.eyebrow }}</span><h3 :id="`lcd-${type}-title`">{{ definition.title }}</h3><p>{{ definition.description }}</p></div><BButton v-if="canManage" type="button" size="sm" variant="primary" :disabled="type === 'coexistence' && !selectedStudentId && !students.length" @click="openCreate"><i class="bx bx-plus"></i> {{ definition.add }}</BButton></header>
    <BAlert v-if="!canManage" show variant="info" class="small mb-0">Vista de consulta. No cuentas con permiso para crear o modificar estos registros.</BAlert>
    <div v-if="type === 'coexistence'" class="lcd-operational__student"><label for="lcd-coexistence-student">Estudiante</label><BFormSelect id="lcd-coexistence-student" v-model="selectedStudentId" size="sm"><option :value="null">Seleccionar estudiante</option><option v-for="student in students" :key="student.id" :value="student.id">{{ studentLabel(student) }}</option></BFormSelect></div>
    <LibroDigitalStatePanel v-if="loading && !items.length" state="loading" compact title="Cargando registros" message="Consultando información autorizada." />
    <LibroDigitalStatePanel v-else-if="error && !items.length" state="error" compact title="No se pudieron cargar los registros" :message="errorMessage(error)" @retry="load" />
    <div v-else-if="items.length" class="table-responsive lcd-operational__table"><table class="table table-hover align-middle mb-0"><caption class="visually-hidden">{{ definition.title }}: registros autorizados visibles</caption><thead><tr><th scope="col">Fecha</th><th scope="col">Estudiante / registro</th><th scope="col">Detalle</th><th scope="col">Estado</th><th v-if="type === 'absences' && canManage" scope="col" class="text-end">Seguimiento</th></tr></thead><tbody><tr v-for="item in items" :key="item.id"><td>{{ formatDate(item.occurred_on || item.service_date || item.opened_on || item.planned_on || item.created_at) }}</td><td><strong>{{ item.student ? studentLabel(item.student) : (item.title || item.name || item.category || definition.title) }}</strong><small>{{ item.category || item.activity_type || item.type || '—' }}</small></td><td><span class="lcd-operational__description">{{ item.description || item.summary || item.objective || item.probable_cause || 'Sin detalle' }}</span></td><td><LibroDigitalStatusBadge :status="item.status || 'active'" /></td><td v-if="type === 'absences' && canManage"><div class="lcd-row-actions"><BButton type="button" size="sm" variant="outline-primary" @click="addAction(item)"><i class="bx bx-plus-circle" aria-hidden="true"></i> Agregar acción</BButton><BButton v-if="!['resolved','closed'].includes(item.status)" type="button" size="sm" variant="outline-success" @click="resolve(item)"><i class="bx bx-check-circle" aria-hidden="true"></i> Resolver</BButton></div></td></tr></tbody></table></div>
    <LibroDigitalStatePanel v-else compact title="Sin registros" :message="definition.empty" />
    <BModal v-model="showForm" :title="definition.add" size="lg" hide-footer>
      <form class="row g-3" @submit.prevent="save"><div v-if="type !== 'parvularia'" class="col-md-7"><label class="form-label" for="lcd-operational-student">Estudiante</label><BFormSelect id="lcd-operational-student" v-model="form.student_profile_id" required><option :value="null">Seleccionar</option><option v-for="student in students" :key="student.id" :value="student.id">{{ studentLabel(student) }}</option></BFormSelect></div><div :class="type === 'parvularia' ? 'col-md-12' : 'col-md-5'"><label class="form-label" for="lcd-operational-date">Fecha</label><BFormInput id="lcd-operational-date" v-model="form.occurred_on" type="date" required /></div><div class="col-md-8"><label class="form-label" for="lcd-operational-title">Título / objetivo</label><BFormInput id="lcd-operational-title" v-model.trim="form.title" maxlength="191" required /></div><div class="col-md-4"><label class="form-label" for="lcd-operational-category">Categoría</label><BFormInput id="lcd-operational-category" v-model.trim="form.category" maxlength="80" /></div><div class="col-12"><label class="form-label" for="lcd-operational-description">Descripción</label><BFormTextarea id="lcd-operational-description" v-model.trim="form.description" rows="4" maxlength="5000" required /></div><div class="col-12"><label class="form-label" for="lcd-operational-actions">Acciones, acuerdos o evidencias</label><BFormTextarea id="lcd-operational-actions" v-model.trim="form.actions" rows="2" maxlength="3000" /></div><div v-if="type === 'coexistence' || type === 'pie'" class="col-md-6"><label class="form-label" for="lcd-operational-confidentiality">Nivel de reserva</label><BFormSelect id="lcd-operational-confidentiality" v-model="form.confidentiality_level"><option value="general">General</option><option value="reserved">Reservada</option><option value="restricted">Restringida</option><option value="high_confidentiality">Alta confidencialidad</option></BFormSelect></div><div class="col-12 d-flex justify-content-end gap-2"><BButton type="button" variant="outline-secondary" @click="showForm = false">Cancelar</BButton><BButton type="submit" variant="primary" :disabled="saving"><span v-if="saving" class="spinner-border spinner-border-sm"></span> Guardar</BButton></div></form>
    </BModal>
  </section>
</template>

<style scoped>
.lcd-operational{display:grid;gap:.9rem;min-width:0;color:var(--lcd-ink,#273244)}.lcd-operational>header{display:flex;align-items:flex-end;justify-content:space-between;gap:.8rem}.lcd-operational>header span{color:var(--lcd-brand-700,#405189);font-size:.7rem;font-weight:800;letter-spacing:.07em}.lcd-operational h3{margin:.12rem 0;color:var(--lcd-ink,#293547);font-size:1.02rem}.lcd-operational header p{margin:0;color:var(--lcd-muted,#748093);font-size:.8rem}.lcd-operational header .btn{display:inline-flex;align-items:center;gap:.35rem;min-height:38px;border-radius:var(--lcd-radius-sm,7px);font-size:.75rem}.lcd-operational__student{display:grid;grid-template-columns:120px minmax(240px,480px);align-items:center;gap:.65rem;padding:.65rem .75rem;border:1px solid var(--lcd-border,#dfe5ec);border-radius:var(--lcd-radius-md,10px);background:var(--lcd-surface-muted,#f6f8fb)}.lcd-operational__student label{color:var(--lcd-ink-soft,#5c697b);font-size:.74rem;font-weight:750}.lcd-operational__student :deep(.form-select){min-height:38px;border-color:var(--lcd-border,#dfe5ec);font-size:.78rem}
.lcd-operational :deep(.btn-sm){min-height:36px}.lcd-operational :deep(.btn:not(.btn-sm)){min-height:40px}.lcd-operational :deep(.form-control),.lcd-operational :deep(.form-select){min-height:40px;font-size:.8rem}.lcd-operational :deep(.form-control-sm),.lcd-operational :deep(.form-select-sm){min-height:36px}
.lcd-operational__table{max-height:600px;border:1px solid var(--lcd-border,#e0e6ed);border-radius:var(--lcd-radius-lg,12px);background:var(--lcd-surface,#fff);box-shadow:var(--lcd-shadow-sm,0 2px 10px rgba(37,47,63,.04))}.lcd-operational__table table{font-size:.78rem}.lcd-operational__table th{position:sticky;z-index:1;top:0;padding:.64rem .7rem;background:var(--lcd-surface-muted,#f5f7fa);color:var(--lcd-muted,#647184);font-size:.69rem;letter-spacing:.04em;text-transform:uppercase}.lcd-operational__table td{padding:.64rem .7rem;border-color:var(--lcd-border,#edf0f4)}.lcd-operational__table td strong,.lcd-operational__table td small{display:block}.lcd-operational__table td small{margin-top:.14rem;color:var(--lcd-muted,#7d8998);font-size:.72rem}.lcd-operational__description{display:-webkit-box;max-width:560px;overflow:hidden;line-height:1.45;-webkit-box-orient:vertical;-webkit-line-clamp:2}.lcd-row-actions{display:flex;justify-content:flex-end;gap:.3rem;white-space:nowrap}.lcd-row-actions :deep(.btn){display:inline-flex;align-items:center;gap:.25rem;min-height:36px;border-radius:6px;font-size:.72rem}.form-label{color:var(--lcd-ink-soft,#536174);font-size:.75rem;font-weight:700}
@media(max-width:700px){.lcd-operational>header{align-items:flex-start;flex-direction:column}.lcd-operational__student{grid-template-columns:1fr}}
</style>
