<script setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { libroDigitalApi } from "../../../services/libro-digital/api";
import LibroDigitalStatePanel from "../LibroDigitalStatePanel.vue";
import { confirmAction, errorMessage, payloadData, payloadItems, showError, showSuccess, studentLabel } from "../module-utils";

const props = defineProps({ session: { type: Object, required: true }, canEdit: { type: Boolean, default: true } });
const emit = defineEmits(["updated", "completed"]);

const loading = ref(false); const error = ref(null); const bundle = ref(null); const rows = ref([]); const search = ref("");
const filter = ref(""); const syncState = ref("saved"); const lastSavedAt = ref(null); const online = ref(navigator.onLine);
let controller = null; let autosaveTimer = null; let saveSequence = 0;

const statuses = computed(() => bundle.value?.catalogs?.attendance_statuses || [
  { value: "present", label: "Presente" }, { value: "absent", label: "Ausente" }, { value: "late", label: "Atraso" }, { value: "left_early", label: "Retiro" }, { value: "not_applicable", label: "No aplica" },
]);
const normalizedStatus = (item) => {
  const option = typeof item === "string"
    ? { value: item, label: item.replaceAll("_", " ") }
    : { value: item.value ?? item.code, label: item.label ?? item.name };
  return option.value === "withdrawn" ? { ...option, value: "left_early", label: option.label || "Retiro" } : option;
};
const visibleRows = computed(() => { const needle = search.value.trim().toLocaleLowerCase("es"); return rows.value.filter((row) => (!filter.value || row.status === filter.value) && (!needle || [studentLabel(row.student || row), row.list_number].filter(Boolean).join(" ").toLocaleLowerCase("es").includes(needle))); });
const totals = computed(() => rows.value.reduce((result, row) => { result.expected += row.status === "not_applicable" ? 0 : 1; result[row.status || "pending"] = (result[row.status || "pending"] || 0) + 1; return result; }, { expected: 0, present: 0, absent: 0, late: 0, left_early: 0, not_applicable: 0, pending: 0 }));
const accounted = computed(() => totals.value.present + totals.value.absent + totals.value.late + totals.value.left_early);
const balanced = computed(() => accounted.value === totals.value.expected && totals.value.pending === 0);
const locked = computed(() => Boolean(!props.canEdit || bundle.value?.locked || ["signed", "closed", "cancelled"].includes(String(props.session.status).toLowerCase())));
const syncLabel = computed(() => ({ saved: lastSavedAt.value ? `Guardado ${lastSavedAt.value.toLocaleTimeString('es-CL', { hour: '2-digit', minute: '2-digit' })}` : "Sin cambios", dirty: "Cambios pendientes", saving: "Guardando…", error: "Error de sincronización", offline: "Sin conexión · pendiente en memoria" }[syncState.value]));

const load = async () => { controller?.abort(); controller = new AbortController(); clearTimeout(autosaveTimer); loading.value = true; error.value = null; try { const payload = await libroDigitalApi.attendance(props.session.id, controller.signal); bundle.value = payloadData(payload); const records = bundle.value.records || bundle.value.attendance || bundle.value.roster || payloadItems(payload); rows.value = records.map((row) => { const status = row.status || row.attendance_status || "pending"; return { ...row, student_profile_id: row.student_profile_id || row.student?.id, status: status === "withdrawn" ? "left_early" : status, arrival_time: row.arrival_time?.slice(0, 5) || "", departure_time: row.departure_time?.slice(0, 5) || "", justification: row.justification || "", observation: row.observation || row.notes || "" }; }); syncState.value = "saved"; } catch (requestError) { if (requestError?.code !== "ERR_CANCELED") error.value = requestError; } finally { loading.value = false; } };
watch(() => props.session.id, load, { immediate: true });

const payload = () => ({ records: rows.value.map((row) => ({ id: row.id || null, roster_snapshot_item_id: row.roster_snapshot_item_id || null, student_profile_id: row.student_profile_id, student_enrollment_id: row.student_enrollment_id || null, status: row.status, arrival_time: row.arrival_time || null, departure_time: row.departure_time || null, justification: row.justification || null, observation: row.observation || null })) });
const save = async () => {
  clearTimeout(autosaveTimer); if (locked.value || syncState.value === "saving") return;
  if (!navigator.onLine) { syncState.value = "offline"; return; }
  const sequence = ++saveSequence; syncState.value = "saving";
  try { const response = await libroDigitalApi.updateAttendance(props.session, bundle.value, payload()); if (sequence !== saveSequence) return; bundle.value = { ...bundle.value, ...payloadData(response) }; syncState.value = "saved"; lastSavedAt.value = new Date(); emit("updated", response); }
  catch (requestError) { if (sequence !== saveSequence) return; syncState.value = "error"; error.value = requestError; if (requestError.isConflict) { await showError(requestError); await load(); } }
};
const scheduleSave = () => { if (locked.value) return; syncState.value = online.value ? "dirty" : "offline"; clearTimeout(autosaveTimer); autosaveTimer = window.setTimeout(save, 900); };
const markAllPresent = () => { rows.value.forEach((row) => { if (row.status !== "not_applicable") row.status = "present"; }); scheduleSave(); };
const complete = async () => { await save(); if (!balanced.value) { await showError(new Error(`Los totales no cuadran: ${accounted.value} registros para ${totals.value.expected} estudiantes esperados.`), "Asistencia incompleta"); return; } const confirmation = await confirmAction({ title: "Completar asistencia", text: "Se validarán los totales. Esta acción no firma automáticamente la sesión.", confirmText: "Completar" }); if (!confirmation.isConfirmed) return; try { const response = await libroDigitalApi.completeAttendance(props.session, bundle.value); bundle.value = { ...bundle.value, ...payloadData(response), locked: true }; emit("completed", response); await showSuccess("Asistencia completada", "La firma docente continúa pendiente hasta realizarla expresamente."); } catch (requestError) { await showError(requestError); } };
const handleOnline = () => { online.value = true; if (["offline", "dirty", "error"].includes(syncState.value)) save(); };
const handleOffline = () => { online.value = false; if (syncState.value !== "saved") syncState.value = "offline"; };
onMounted(() => { window.addEventListener("online", handleOnline); window.addEventListener("offline", handleOffline); });
onBeforeUnmount(() => { controller?.abort(); clearTimeout(autosaveTimer); window.removeEventListener("online", handleOnline); window.removeEventListener("offline", handleOffline); });
</script>

<template>
  <section class="lcd-attendance" aria-labelledby="lcd-attendance-title" :aria-busy="loading || syncState === 'saving'">
    <header class="lcd-attendance__heading"><div><span>REGISTRO RÁPIDO</span><h3 id="lcd-attendance-title">Asistencia por bloque</h3><p>Los cambios se guardan de forma controlada; la firma siempre es una acción separada.</p></div><div class="lcd-sync" :class="`lcd-sync--${syncState}`" role="status" aria-live="polite"><span class="lcd-sync__dot" aria-hidden="true"></span><i v-if="syncState === 'saving'" class="bx bx-loader-alt bx-spin" aria-hidden="true"></i>{{ syncLabel }}</div></header>
    <LibroDigitalStatePanel v-if="loading && !bundle" state="loading" compact title="Cargando nómina" message="Preparando el snapshot aplicable a la sesión." />
    <LibroDigitalStatePanel v-else-if="error && !bundle" state="error" compact title="No se pudo cargar la asistencia" :message="errorMessage(error)" @retry="load" />
    <template v-else>
      <BAlert v-if="locked" show variant="info" class="small">{{ canEdit ? 'La sesión está bloqueada. Cualquier cambio requiere una solicitud formal de corrección.' : 'Vista de solo lectura. No cuentas con permiso para modificar la asistencia.' }}</BAlert>
      <BAlert v-else-if="syncState === 'offline'" show variant="warning" class="small">Los cambios permanecen únicamente en memoria hasta recuperar la conexión. No cierres esta pestaña.</BAlert>
      <BAlert v-else-if="syncState === 'error'" show variant="danger" class="small">No se pudo sincronizar. <button type="button" class="btn btn-link btn-sm p-0" @click="save">Reintentar</button></BAlert>
      <div class="lcd-attendance__totals" :class="{ 'is-unbalanced': !balanced }" aria-live="polite"><div><span>Esperadas</span><strong>{{ totals.expected }}</strong></div><div><span>Presentes</span><strong>{{ totals.present }}</strong></div><div><span>Ausentes</span><strong>{{ totals.absent }}</strong></div><div><span>Atrasos</span><strong>{{ totals.late }}</strong></div><div><span>Retiros</span><strong>{{ totals.left_early }}</strong></div><div><span>Cuadratura</span><strong>{{ accounted }}/{{ totals.expected }}</strong></div></div>
      <div class="lcd-attendance__toolbar"><div class="input-group input-group-sm"><span class="input-group-text"><i class="bx bx-search"></i></span><BFormInput v-model="search" placeholder="Buscar estudiante o número de lista" aria-label="Buscar estudiante" /></div><BFormSelect v-model="filter" size="sm" aria-label="Filtrar por estado"><option value="">Todos los estados</option><option v-for="option in statuses.map(normalizedStatus)" :key="option.value" :value="option.value">{{ option.label }}</option></BFormSelect><BButton type="button" size="sm" variant="outline-success" :disabled="locked" @click="markAllPresent"><i class="bx bx-check-double"></i> Marcar todas presentes</BButton></div>
      <div class="table-responsive lcd-attendance__table"><table class="table table-hover align-middle mb-0"><caption class="visually-hidden">Registro de asistencia de la nómina aplicable a esta sesión</caption><thead><tr><th scope="col">N.º</th><th scope="col">Estudiante</th><th scope="col">Estado</th><th scope="col">Hora llegada</th><th scope="col">Hora salida</th><th scope="col">Justificación</th><th scope="col">Observación</th></tr></thead><tbody><tr v-for="row in visibleRows" :key="row.student_profile_id || row.id" :class="`is-${row.status || 'pending'}`"><td>{{ row.list_number || '—' }}</td><td><strong>{{ studentLabel(row.student || row) }}</strong><small v-if="row.enrollment_status">{{ row.enrollment_status }}</small></td><td><select v-model="row.status" class="form-select form-select-sm" :disabled="locked" :aria-label="`Estado de ${studentLabel(row.student || row)}`" @change="scheduleSave"><option value="pending">Pendiente</option><option v-for="option in statuses.map(normalizedStatus)" :key="option.value" :value="option.value">{{ option.label }}</option></select></td><td><input v-model="row.arrival_time" type="time" class="form-control form-control-sm" :disabled="locked || row.status !== 'late'" :aria-label="`Hora de llegada de ${studentLabel(row.student || row)}`" @change="scheduleSave" /></td><td><input v-model="row.departure_time" type="time" class="form-control form-control-sm" :disabled="locked || row.status !== 'left_early'" :aria-label="`Hora de salida de ${studentLabel(row.student || row)}`" @change="scheduleSave" /></td><td><input v-model.trim="row.justification" type="text" class="form-control form-control-sm" maxlength="255" :disabled="locked" :aria-label="`Justificación de ${studentLabel(row.student || row)}`" @change="scheduleSave" /></td><td><input v-model.trim="row.observation" type="text" class="form-control form-control-sm" maxlength="500" :disabled="locked" :aria-label="`Observación de ${studentLabel(row.student || row)}`" @change="scheduleSave" /></td></tr></tbody></table></div>
      <LibroDigitalStatePanel v-if="!visibleRows.length" compact title="Sin estudiantes visibles" message="Ajusta la búsqueda o el filtro de estado." />
      <footer class="lcd-attendance__footer"><span :class="balanced ? 'text-success' : 'text-danger'"><i class="bx" :class="balanced ? 'bx-check-circle' : 'bx-error-circle'"></i> {{ balanced ? 'Totales cuadrados' : 'Faltan registros o los totales no cuadran' }}</span><div><BButton type="button" size="sm" variant="outline-primary" :disabled="locked || syncState === 'saving'" @click="save">Guardar ahora</BButton><BButton type="button" size="sm" variant="primary" :disabled="locked || !balanced" @click="complete">Completar asistencia</BButton></div></footer>
    </template>
  </section>
</template>

<style scoped>
.lcd-attendance{display:grid;gap:.9rem;min-width:0;color:var(--lcd-ink,#273244)}
.lcd-attendance :deep(.btn-sm){min-height:36px}.lcd-attendance :deep(.btn:not(.btn-sm)){min-height:40px}
.lcd-attendance__heading{display:flex;align-items:flex-start;justify-content:space-between;gap:1rem}.lcd-attendance__heading>div>span{color:var(--lcd-brand-700,#405189);font-size:.7rem;font-weight:800;letter-spacing:.07em}.lcd-attendance__heading h3{margin:.12rem 0;color:var(--lcd-ink,#293547);font-size:1.02rem}.lcd-attendance__heading p{margin:0;color:var(--lcd-muted,#748093);font-size:.8rem}
.lcd-sync{display:flex;align-items:center;gap:.38rem;min-height:36px;padding:.4rem .6rem;border:1px solid var(--lcd-border,#dfe5ec);border-radius:999px;background:var(--lcd-surface,#fff);box-shadow:var(--lcd-shadow-sm,0 2px 8px rgba(37,47,63,.04));color:var(--lcd-ink-soft,#667386);font-size:.72rem;font-weight:650;white-space:nowrap}.lcd-sync__dot{width:8px;height:8px;border-radius:50%;background:var(--lcd-success,#1f9d69)}.lcd-sync--dirty .lcd-sync__dot,.lcd-sync--saving .lcd-sync__dot{background:var(--lcd-warning,#d19a26)}.lcd-sync--error .lcd-sync__dot,.lcd-sync--offline .lcd-sync__dot{background:var(--lcd-danger,#c44351)}
.lcd-attendance__totals{display:grid;grid-template-columns:repeat(6,1fr);overflow:hidden;border:1px solid var(--lcd-border,#dfe5ec);border-radius:var(--lcd-radius-md,10px);background:var(--lcd-surface,#fff);box-shadow:var(--lcd-shadow-sm,0 2px 8px rgba(37,47,63,.04))}.lcd-attendance__totals div{padding:.7rem .75rem;border-right:1px solid var(--lcd-border,#e5e9ef)}.lcd-attendance__totals div:last-child{border-right:0}.lcd-attendance__totals span,.lcd-attendance__totals strong{display:block}.lcd-attendance__totals span{color:var(--lcd-muted,#758194);font-size:.7rem}.lcd-attendance__totals strong{margin-top:.08rem;color:var(--lcd-ink,#2d394b);font-size:1rem}.lcd-attendance__totals div:last-child{background:color-mix(in srgb,var(--lcd-success,#0ab39c) 7%,var(--lcd-surface,#fff))}.lcd-attendance__totals.is-unbalanced div:last-child{background:color-mix(in srgb,var(--lcd-danger,#f06548) 8%,var(--lcd-surface,#fff));color:var(--lcd-danger,#c44351)}
.lcd-attendance__toolbar{display:grid;grid-template-columns:minmax(240px,1fr) 210px auto;gap:.55rem;padding:.55rem;border:1px solid var(--lcd-border,#dfe5ec);border-radius:var(--lcd-radius-md,10px);background:var(--lcd-surface-muted,#f6f8fb)}.lcd-attendance__toolbar :deep(.form-control),.lcd-attendance__toolbar :deep(.form-select),.lcd-attendance__toolbar :deep(.input-group-text){min-height:38px;border-color:var(--lcd-border,#dfe5ec);font-size:.78rem}.lcd-attendance__toolbar .btn{display:inline-flex;align-items:center;justify-content:center;gap:.35rem;min-height:38px;border-radius:var(--lcd-radius-sm,7px);font-size:.75rem}
.lcd-attendance__table{max-height:600px;border:1px solid var(--lcd-border,#e0e6ed);border-radius:var(--lcd-radius-lg,12px);background:var(--lcd-surface,#fff);box-shadow:var(--lcd-shadow-sm,0 2px 10px rgba(37,47,63,.04))}.lcd-attendance__table table{font-size:.78rem}.lcd-attendance__table th{position:sticky;z-index:2;top:0;padding:.65rem .6rem;background:var(--lcd-surface-muted,#f5f7fa);color:var(--lcd-muted,#647184);font-size:.69rem;letter-spacing:.04em;text-transform:uppercase}.lcd-attendance__table td{padding:.48rem .6rem;border-color:var(--lcd-border,#edf0f4)}.lcd-attendance__table tbody tr{box-shadow:inset 3px 0 transparent;transition:var(--lcd-transition,background .15s ease)}.lcd-attendance__table tbody tr.is-absent{box-shadow:inset 3px 0 var(--lcd-danger,#f06548)}.lcd-attendance__table tbody tr.is-late,.lcd-attendance__table tbody tr.is-left_early{box-shadow:inset 3px 0 var(--lcd-warning,#f7b84b)}.lcd-attendance__table tbody tr.is-present{box-shadow:inset 3px 0 var(--lcd-success,#0ab39c)}.lcd-attendance__table td strong,.lcd-attendance__table td small{display:block}.lcd-attendance__table td small{margin-top:.1rem;color:var(--lcd-muted,#7d8998);font-size:.7rem}.lcd-attendance__table .form-control,.lcd-attendance__table .form-select{min-width:125px;min-height:36px;border-color:var(--lcd-border,#dfe5ec);font-size:.76rem}.lcd-attendance__table .form-control:focus,.lcd-attendance__table .form-select:focus{border-color:var(--lcd-brand-500,#5268a3);box-shadow:0 0 0 3px var(--lcd-focus,rgba(64,81,137,.18))}.lcd-attendance__table :disabled{background:var(--lcd-surface-muted,#f5f7fa);color:var(--lcd-muted,#758194);opacity:.85}
.lcd-attendance__footer{display:flex;align-items:center;justify-content:space-between;gap:.8rem;padding:.65rem .75rem;border:1px solid var(--lcd-border,#dfe5ec);border-radius:var(--lcd-radius-md,10px);background:var(--lcd-surface,#fff)}.lcd-attendance__footer>span{display:inline-flex;align-items:center;gap:.35rem;font-size:.76rem;font-weight:700}.lcd-attendance__footer>div{display:flex;gap:.4rem}.lcd-attendance__footer :deep(.btn){min-height:38px;border-radius:var(--lcd-radius-sm,7px);font-size:.75rem}
@media(max-width:1000px){.lcd-attendance__totals{grid-template-columns:repeat(3,1fr)}.lcd-attendance__totals div:nth-child(3){border-right:0}.lcd-attendance__totals div:nth-child(n+4){border-top:1px solid var(--lcd-border,#e5e9ef)}.lcd-attendance__toolbar{grid-template-columns:1fr 1fr}.lcd-attendance__toolbar .btn{grid-column:1/-1}}
@media(max-width:640px){.lcd-attendance__heading,.lcd-attendance__footer{align-items:stretch;flex-direction:column}.lcd-sync{align-self:flex-start}.lcd-attendance__toolbar{grid-template-columns:1fr}.lcd-attendance__toolbar .btn{grid-column:auto}.lcd-attendance__footer>div{display:grid;grid-template-columns:1fr 1fr}.lcd-attendance__totals{grid-template-columns:repeat(2,1fr)}.lcd-attendance__totals div:nth-child(2n){border-right:0}.lcd-attendance__totals div:nth-child(3){border-right:1px solid var(--lcd-border,#e5e9ef)}.lcd-attendance__totals div:nth-child(n+3){border-top:1px solid var(--lcd-border,#e5e9ef)}}
@media(prefers-reduced-motion:reduce){.lcd-attendance__table tbody tr{transition:none}}
</style>
