<script setup>
import { onMounted, ref } from "vue";
import axios from "axios";
import Swal from "sweetalert2";
import { waitForAndDownloadAttendanceExport } from "../../utils/attendance-export";

const props = defineProps({ filters: { type: Object, required: true }, capabilities: { type: Object, default: () => ({}) } });
const exports = ref([]); const running = ref("");
const reports = [
  { type: "institutional_management", title: "Gestión institucional", description: "Resumen ejecutivo, cursos, niveles de riesgo, patrones, pendientes y efectividad.", icon: "bx-buildings", tone: "navy", formats: ["pdf", "xls"] },
  { type: "course_management", title: "Gestión por curso", description: "Asistencia, estudiantes priorizados, patrones y expedientes del curso seleccionado.", icon: "bx-chalkboard", tone: "blue", formats: ["pdf", "xls"], needsCourse: true },
  { type: "critical_cases", title: "Casos críticos", description: "Listado operativo acotado a expedientes críticos y su estado de intervención.", icon: "bx-error-circle", tone: "red", formats: ["pdf", "xls"] },
  { type: "intervention_effectiveness", title: "Efectividad observada", description: "Variación posterior a planes evaluados, con advertencia explícita de no causalidad.", icon: "bx-line-chart", tone: "green", formats: ["pdf", "xls"] },
];
const loadExports = async () => { try { const { data } = await axios.get("/api/attendance-statistics/exports"); exports.value = data.data || []; } catch { exports.value = []; } };
const run = async (report, format) => { if (report.needsCourse && !props.filters.course_section_id) { await Swal.fire({ icon: "info", title: "Selecciona un curso", text: "Usa el filtro superior para emitir este reporte." }); return; } running.value = `${report.type}-${format}`; let progress=false; try { const response = await axios.post("/api/attendance-statistics/exports", { academic_year_id: Number(props.filters.academic_year_id), report_type: report.type, format, filters: { ...props.filters } }); Swal.fire({ title: "Construyendo reporte", text: "Se aplican permisos, alcance y filtros actuales.", allowOutsideClick: false, didOpen: () => Swal.showLoading() }); progress=true; await waitForAndDownloadAttendanceExport(response.data); Swal.close(); progress=false; await loadExports(); } catch (requestError) { if(progress)Swal.close(); await Swal.fire({ icon: requestError.code === "ATTENDANCE_EXPORT_TIMEOUT" ? "info" : "error", title: requestError.code === "ATTENDANCE_EXPORT_TIMEOUT" ? "El reporte continúa" : "No se pudo generar", text: requestError.response?.data?.message || requestError.message || "Intenta nuevamente." }); } finally { running.value=""; } };
const download = (item) => { if (item.download_url) window.location.assign(item.download_url); };
onMounted(loadExports);
</script>

<template>
  <section class="reports-stack">
    <div class="method-note"><i class="bx bx-file"></i><div><strong>Reportes filtrados y trazables</strong><p>Cada archivo incluye fuente, periodo, filtros, fecha, emisor, definiciones y limitaciones metodológicas. Los datos nominales respetan el alcance autorizado.</p></div></div>
    <div class="report-grid"><article v-for="report in reports" :key="report.type" class="report-card"><span class="report-icon" :class="report.tone"><i class="bx" :class="report.icon"></i></span><div class="report-copy"><h2>{{ report.title }}</h2><p>{{ report.description }}</p><small v-if="report.needsCourse"><i class="bx bx-filter-alt"></i>Requiere curso seleccionado</small></div><div class="format-actions"><button v-for="format in report.formats" :key="format" type="button" :disabled="Boolean(running)" @click="run(report,format)"><span v-if="running===`${report.type}-${format}`" class="spinner-border spinner-border-sm"></span><i v-else class="bx" :class="format==='pdf'?'bxs-file-pdf':'bx-spreadsheet'"></i>{{ format.toUpperCase() }}</button></div></article></div>
    <article class="history"><header><div><span>HISTORIAL</span><h2>Archivos generados por ti</h2></div><button type="button" @click="loadExports"><i class="bx bx-refresh"></i>Actualizar</button></header><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Reporte</th><th>Formato</th><th>Estado</th><th>Tamaño</th><th>Terminado</th><th></th></tr></thead><tbody><tr v-for="item in exports" :key="item.id"><td>{{ item.report_type.replaceAll('_',' ') }}</td><td>{{ item.format.toUpperCase() }}</td><td><span class="export-status" :class="item.status">{{ item.status }}</span></td><td>{{ item.file_size ? `${(item.file_size/1024).toLocaleString('es-CL',{maximumFractionDigits:1})} KB` : '—' }}</td><td>{{ item.completed_at ? new Date(item.completed_at).toLocaleString('es-CL') : '—' }}</td><td><button v-if="item.download_url" type="button" class="download" @click="download(item)"><i class="bx bx-download"></i>Descargar</button><span v-else-if="item.status==='failed'" class="failed" :title="item.failure_message">Error</span><span v-else>{{ item.progress || 0 }}%</span></td></tr><tr v-if="!exports.length"><td colspan="6"><div class="empty"><i class="bx bx-archive"></i>Aún no hay reportes generados.</div></td></tr></tbody></table></div></article>
  </section>
</template>

<style scoped>
.reports-stack{display:grid;gap:.9rem}.method-note{display:flex;gap:.75rem;border:1px solid #d5deec;border-left:4px solid #405189;border-radius:10px;background:#f8f9fd;padding:.85rem 1rem;color:#536175}.method-note>i{font-size:1.45rem;color:#405189}.method-note strong{font-size:.71rem}.method-note p{margin:.15rem 0 0;font-size:.63rem}.report-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:.8rem}.report-card{display:grid;grid-template-columns:46px 1fr auto;align-items:center;gap:.75rem;border:1px solid #e0e6ed;border-radius:11px;background:#fff;padding:.9rem;box-shadow:0 5px 16px rgba(29,41,61,.035)}.report-icon{display:grid;place-items:center;height:44px;border-radius:10px;font-size:1.25rem}.report-icon.navy{background:#edf0f7;color:#405189}.report-icon.blue{background:#e9f2f8;color:#39789d}.report-icon.red{background:#ffebed;color:#bd3543}.report-icon.green{background:#e7f6ef;color:#268263}.report-copy h2{margin:0;color:#344157;font-size:.78rem}.report-copy p{margin:.16rem 0;color:#7a8798;font-size:.59rem}.report-copy small{color:#a35b12;font-size:.54rem}.format-actions{display:flex;gap:.3rem}.format-actions button{display:flex;align-items:center;gap:.22rem;border:1px solid #dce2e9;border-radius:6px;background:#fff;padding:.4rem .5rem;color:#536176;font-size:.58rem;font-weight:750}.format-actions button:hover{border-color:#9ba8c2;color:#405189}.history{overflow:hidden;border:1px solid #e0e6ed;border-radius:11px;background:#fff}.history>header{display:flex;align-items:center;justify-content:space-between;padding:.8rem .9rem}.history header span{color:#64759b;font-size:.54rem;font-weight:850;letter-spacing:.1em}.history h2{margin:.1rem 0;color:#344157;font-size:.8rem}.history header button{border:0;background:transparent;color:#405189;font-size:.6rem;font-weight:750}.table{font-size:.65rem}.table thead th{border-bottom:1px solid #e0e5eb;background:#f7f8fa;color:#69768a;font-size:.57rem}.table td{border-color:#eef1f4;color:#3e4a5c;text-transform:capitalize}.export-status{border-radius:999px;background:#f0f2f5;padding:.22rem .42rem;font-size:.54rem}.export-status.completed{background:#e8f7f0;color:#197156}.export-status.failed{background:#ffebed;color:#b83240}.export-status.processing,.export-status.queued{background:#e9f1fb;color:#365f90}.download{border:0;background:transparent;color:#405189;font-size:.58rem;font-weight:750}.failed{color:#b83240}.empty{display:flex;align-items:center;justify-content:center;gap:.4rem;min-height:120px;color:#8490a0;font-size:.65rem}@media(max-width:950px){.report-grid{grid-template-columns:1fr}}@media(max-width:560px){.report-card{grid-template-columns:42px 1fr}.format-actions{grid-column:1/-1}.format-actions button{flex:1;justify-content:center}}
</style>
