<?php

return [
    'storage' => [
        'disk' => env('CLASS_PRESENTATIONS_DISK', 'local'),
        'root' => trim((string) env('CLASS_PRESENTATIONS_ROOT', 'private/class-presentations'), '/'),
        'max_reference_file_kb' => (int) env('CLASS_PRESENTATIONS_MAX_REFERENCE_FILE_KB', 15360),
        'max_reference_files' => (int) env('CLASS_PRESENTATIONS_MAX_REFERENCE_FILES', 5),
        'max_extracted_characters_per_file' => (int) env('CLASS_PRESENTATIONS_MAX_EXTRACTED_CHARACTERS_PER_FILE', 30000),
        'max_extracted_characters_total' => (int) env('CLASS_PRESENTATIONS_MAX_EXTRACTED_CHARACTERS_TOTAL', 70000),
    ],

    'openai' => [
        'api_key' => env('OPENAI_API_KEY'),
        'base_url' => rtrim((string) env('OPENAI_BASE_URL', 'https://api.openai.com/v1'), '/'),
        'model' => env('OPENAI_PRESENTATION_MODEL', 'gpt-5.6'),
        'timeout_seconds' => (int) env('OPENAI_PRESENTATION_TIMEOUT', 300),
        'max_output_tokens' => (int) env('OPENAI_PRESENTATION_MAX_OUTPUT_TOKENS', 30000),
        'reasoning_effort' => env('OPENAI_PRESENTATION_REASONING_EFFORT', 'medium'),
        'prompt_name' => 'class-presentation',
        'prompt_version' => 'v3.0.0',
    ],

    'generation' => [
        'queue' => env('CLASS_PRESENTATIONS_QUEUE', 'class-presentations'),
        'node_binary' => env('CLASS_PRESENTATIONS_NODE_BINARY', 'node'),
        'builder_script' => base_path('scripts/class-presentations/build-deck.mjs'),
        'teacher_guide_builder_script' => base_path('scripts/class-presentations/build-teacher-guide.mjs'),
        'process_timeout_seconds' => (int) env('CLASS_PRESENTATIONS_PROCESS_TIMEOUT', 180),
        'teacher_guide_process_timeout_seconds' => (int) env('CLASS_PRESENTATIONS_TEACHER_GUIDE_PROCESS_TIMEOUT', 180),
        'libreoffice_binary' => env('CLASS_PRESENTATIONS_LIBREOFFICE_BINARY', 'soffice'),
        'pdftoppm_binary' => env('CLASS_PRESENTATIONS_PDFTOPPM_BINARY', 'pdftoppm'),
        'external_process_timeout_seconds' => (int) env('CLASS_PRESENTATIONS_EXTERNAL_PROCESS_TIMEOUT', 180),
        'per_user_per_day' => (int) env('CLASS_PRESENTATIONS_DAILY_USER_QUOTA', 20),
        'poll_interval_ms' => 5000,
    ],

    'options' => [
        'class_type' => [
            'introduction' => 'Introducción',
            'content_development' => 'Desarrollo de contenido',
            'application' => 'Aplicación',
            'review' => 'Repaso',
            'practical_workshop' => 'Taller práctico',
            'formative_assessment' => 'Evaluación formativa',
            'unit_closure' => 'Cierre de unidad',
        ],
        'duration_minutes' => [45, 60, 90, 120],
        'slide_count' => [6, 8, 10, 12, 15, 20],
        'prior_knowledge' => [
            'initial' => 'Iniciales', 'basic' => 'Básicos', 'intermediate' => 'Intermedios',
            'advanced' => 'Avanzados', 'automatic' => 'Inferir automáticamente según el curso',
        ],
        'depth' => [
            'introductory' => 'Introductorio', 'intermediate' => 'Intermedio', 'deep' => 'Profundo',
            'automatic' => 'Automático según el nivel',
        ],
        'methodology' => [
            'guided_exposition' => 'Exposición guiada', 'cooperative_learning' => 'Aprendizaje cooperativo',
            'problem_based_learning' => 'Aprendizaje basado en problemas', 'case_study' => 'Estudio de caso',
            'practical_workshop' => 'Taller práctico', 'inquiry' => 'Indagación',
            'dialogued_class' => 'Clase dialogada', 'automatic' => 'Automática según el objetivo',
        ],
        'tone' => [
            'academic' => 'Académico', 'close' => 'Cercano', 'motivating' => 'Motivador',
            'formal' => 'Formal', 'playful' => 'Lúdico', 'reflective' => 'Reflexivo',
        ],
        'opening' => [
            'problematizing_question' => 'Pregunta problematizadora', 'everyday_situation' => 'Situación cotidiana',
            'trigger_image' => 'Imagen detonante', 'relevant_fact' => 'Dato relevante',
            'brief_case' => 'Caso breve', 'none' => 'Sin apertura especial',
        ],
        'activity' => [
            'none' => 'Sin actividad', 'individual' => 'Individual', 'pairs' => 'En parejas', 'group' => 'Grupal',
            'guided_discussion' => 'Discusión guiada', 'case_analysis' => 'Análisis de caso',
            'practical_production' => 'Producción práctica', 'educational_game' => 'Juego pedagógico',
        ],
        'assessment' => [
            'none' => 'Sin evaluación', 'exit_ticket' => 'Ticket de salida',
            'checking_questions' => 'Preguntas de comprobación', 'checklist' => 'Lista de cotejo',
            'rating_scale' => 'Escala de apreciación', 'self_assessment' => 'Autoevaluación',
            'peer_assessment' => 'Coevaluación', 'short_quiz' => 'Cuestionario breve',
        ],
        'aspect_ratio' => ['wide' => '16:9', 'standard' => '4:3'],
        'visual_style' => [
            'institutional' => 'Institucional', 'academic' => 'Académico', 'minimalist' => 'Minimalista',
            'contemporary' => 'Contemporáneo', 'infographic' => 'Infográfico', 'youth' => 'Juvenil',
            'children' => 'Infantil',
        ],
        'palette' => [
            'institutional' => 'Institucional', 'blue' => 'Azul', 'green' => 'Verde', 'violet' => 'Violeta',
            'warm' => 'Cálida', 'neutral' => 'Neutra', 'automatic' => 'Automática según asignatura',
        ],
        'visual_resources' => [
            'editable' => 'Formas, iconos y diagramas editables', 'images' => 'Imágenes',
            'charts' => 'Gráficos, cuando existan datos', 'timeline' => 'Línea de tiempo, cuando corresponda',
            'automatic' => 'Automático',
        ],
    ],

    'multiple_options' => [
        'methodology' => ['min' => 1, 'max' => 3, 'exclusive' => ['automatic']],
        'activity' => ['min' => 1, 'max' => 3, 'exclusive' => ['none']],
        'assessment' => ['min' => 1, 'max' => 3, 'exclusive' => ['none']],
        'visual_resources' => ['min' => 1, 'max' => 4, 'exclusive' => ['automatic']],
    ],

    'option_descriptions' => [
        'methodology' => [
            'guided_exposition' => 'Explicación breve con andamiaje y comprobaciones.',
            'cooperative_learning' => 'Roles y propósito común para aprender con otras personas.',
            'problem_based_learning' => 'El contenido se organiza desde un desafío auténtico.',
            'case_study' => 'Analiza una situación concreta antes de generalizar.',
            'practical_workshop' => 'Prioriza producción, ensayo y retroalimentación.',
            'inquiry' => 'Observa, formula preguntas y construye explicaciones.',
            'dialogued_class' => 'La comprensión avanza mediante preguntas y conversación guiada.',
            'automatic' => 'El sistema elige una estrategia coherente con el objetivo.',
        ],
        'activity' => [
            'none' => 'No se reservará una diapositiva de actividad.',
            'individual' => 'Trabajo personal con producto o respuesta verificable.',
            'pairs' => 'Intercambio breve en duplas con una consigna común.',
            'group' => 'Colaboración en equipos con roles o producto compartido.',
            'guided_discussion' => 'Conversación estructurada con preguntas y acuerdos.',
            'case_analysis' => 'Aplicación de criterios a una situación concreta.',
            'practical_production' => 'El curso crea, construye o demuestra algo observable.',
            'educational_game' => 'Desafío lúdico con una finalidad pedagógica explícita.',
        ],
        'assessment' => [
            'none' => 'No se incluirá una instancia evaluativa.',
            'exit_ticket' => 'Evidencia individual breve al terminar la clase.',
            'checking_questions' => 'Preguntas para comprobar ideas esenciales durante la clase.',
            'checklist' => 'Criterios observables para revisar un desempeño o producto.',
            'rating_scale' => 'Gradúa el nivel de logro con descriptores claros.',
            'self_assessment' => 'Cada estudiante revisa su propio proceso o aprendizaje.',
            'peer_assessment' => 'Compañeros retroalimentan con criterios protegidos.',
            'short_quiz' => 'Comprobación breve de contenidos ya enseñados.',
        ],
        'visual_resources' => [
            'editable' => 'Prioriza diagramas y objetos que puedan modificarse en PowerPoint.',
            'images' => 'Incluye sugerencias visuales concretas cuando aporten comprensión.',
            'charts' => 'Usa gráficos editables solo si existen datos reales.',
            'timeline' => 'Representa secuencias o procesos temporales cuando corresponda.',
            'automatic' => 'El sistema selecciona los recursos según cada diapositiva.',
        ],
        'visual_style' => [
            'institutional' => 'Sobrio, ordenado y consistente con comunicación escolar formal.',
            'academic' => 'Editorial, reflexivo y apropiado para contenido de mayor profundidad.',
            'minimalist' => 'Máximo aire visual, jerarquía limpia y pocos elementos por lámina.',
            'contemporary' => 'Composición dinámica, tipografía firme y acentos actuales.',
            'infographic' => 'Datos, procesos y relaciones explicados visualmente.',
            'youth' => 'Enérgico y cercano, sin perder legibilidad ni rigor.',
            'children' => 'Lúdico, cálido y concreto; usa formas amables y lectura muy clara.',
        ],
        'palette' => [
            'institutional' => 'Azul, turquesa y acentos cálidos equilibrados.',
            'blue' => 'Familia de azules con alto contraste.',
            'green' => 'Verdes naturales con acento cálido.',
            'violet' => 'Violetas expresivos con contraste editorial.',
            'warm' => 'Terracotas, naranjos y fondos crema.',
            'neutral' => 'Grises azulados y acentos discretos.',
            'automatic' => 'La asignatura y el estilo determinan la combinación.',
        ],
    ],

    'palette_tokens' => [
        'institutional' => ['primary' => '173F67', 'secondary' => '1A8D86', 'accent' => 'F2A65A', 'accent_alt' => 'E45B5B', 'ink' => '17243A', 'muted' => '5F6F82', 'soft' => 'EAF4F3', 'background' => 'F7FAFC'],
        'blue' => ['primary' => '2458A6', 'secondary' => '2F80ED', 'accent' => '56CCF2', 'accent_alt' => 'F2A65A', 'ink' => '17243A', 'muted' => '5F6F82', 'soft' => 'EAF2FC', 'background' => 'F8FAFD'],
        'green' => ['primary' => '276749', 'secondary' => '319795', 'accent' => 'F6AD55', 'accent_alt' => 'D95D6A', 'ink' => '18392B', 'muted' => '5F6F82', 'soft' => 'E7F5EF', 'background' => 'F8FCFA'],
        'violet' => ['primary' => '5B3F8C', 'secondary' => '805AD5', 'accent' => 'ED64A6', 'accent_alt' => 'F2B84B', 'ink' => '2D2440', 'muted' => '6B607A', 'soft' => 'F1ECFA', 'background' => 'FBF9FD'],
        'warm' => ['primary' => '9C4221', 'secondary' => 'DD6B20', 'accent' => 'D69E2E', 'accent_alt' => '2A9D8F', 'ink' => '3C2A22', 'muted' => '745D50', 'soft' => 'FFF3E8', 'background' => 'FFFCF8'],
        'neutral' => ['primary' => '334155', 'secondary' => '64748B', 'accent' => '0F766E', 'accent_alt' => 'D97706', 'ink' => '1E293B', 'muted' => '64748B', 'soft' => 'EEF2F6', 'background' => 'FAFBFC'],
    ],

    'children_palette_tokens' => [
        'institutional' => ['primary' => '4055A8', 'secondary' => '18A999', 'accent' => 'FFB627', 'accent_alt' => 'FF6B6B', 'ink' => '25324B', 'muted' => '5C6880', 'soft' => 'EAF8F4', 'background' => 'FFFDF7'],
        'blue' => ['primary' => '3D5AFE', 'secondary' => '22B8CF', 'accent' => 'FFD43B', 'accent_alt' => 'FF6B6B', 'ink' => '26324B', 'muted' => '5E6A82', 'soft' => 'EAF6FF', 'background' => 'FFFDF8'],
        'green' => ['primary' => '2F855A', 'secondary' => '20B486', 'accent' => 'FFC857', 'accent_alt' => 'FF6B6B', 'ink' => '243B35', 'muted' => '5A7069', 'soft' => 'EAF9EF', 'background' => 'FFFDF7'],
        'violet' => ['primary' => '7048E8', 'secondary' => 'AE3EC9', 'accent' => 'FFD43B', 'accent_alt' => 'FF6B81', 'ink' => '352B50', 'muted' => '716783', 'soft' => 'F5EEFF', 'background' => 'FFFBFF'],
        'warm' => ['primary' => 'E8590C', 'secondary' => 'F08C00', 'accent' => 'FFD43B', 'accent_alt' => '20A39E', 'ink' => '4A3024', 'muted' => '786052', 'soft' => 'FFF1DB', 'background' => 'FFFCF5'],
        'neutral' => ['primary' => '455A64', 'secondary' => '26A69A', 'accent' => 'FFCA28', 'accent_alt' => 'EF6C72', 'ink' => '2E3A40', 'muted' => '65747B', 'soft' => 'EDF7F6', 'background' => 'FFFDF8'],
    ],

    'style_profiles' => [
        'institutional' => [
            'description' => 'Sistema sobrio y confiable para comunicación escolar formal.',
            'heading_font' => 'Aptos Display', 'body_font' => 'Aptos', 'geometry' => 'structured',
            'traits' => ['Jerarquía formal', 'Retícula estable', 'Acentos discretos'],
            'composition_rules' => ['Usa alineaciones regulares y márgenes consistentes.', 'Prioriza claridad, autoridad y lectura ejecutiva.'],
            'avoid' => ['decoración infantil', 'composición caótica', 'colores estridentes'],
        ],
        'academic' => [
            'description' => 'Lenguaje editorial para explicar ideas con profundidad y calma.',
            'heading_font' => 'Georgia', 'body_font' => 'Aptos', 'geometry' => 'editorial',
            'traits' => ['Títulos editoriales', 'Ritmo pausado', 'Contraste sobrio'],
            'composition_rules' => ['Combina una tipografía editorial con cuerpo altamente legible.', 'Reserva espacio para argumentos, citas o comparaciones.'],
            'avoid' => ['estética de videojuego', 'ornamentos gratuitos', 'densidad excesiva'],
        ],
        'minimalist' => [
            'description' => 'Presentación esencial, espaciosa y de foco único.',
            'heading_font' => 'Aptos Display', 'body_font' => 'Aptos', 'geometry' => 'minimal',
            'traits' => ['Mucho aire', 'Foco único', 'Acento preciso'],
            'composition_rules' => ['Reduce el número de elementos simultáneos.', 'Usa escala tipográfica y espacio, no contenedores repetidos, para crear jerarquía.'],
            'avoid' => ['rejillas de tarjetas', 'decoración redundante', 'texto denso'],
        ],
        'contemporary' => [
            'description' => 'Composición actual, enérgica y geométrica.',
            'heading_font' => 'Trebuchet MS', 'body_font' => 'Aptos', 'geometry' => 'dynamic',
            'traits' => ['Bloques asimétricos', 'Escala tipográfica', 'Movimiento controlado'],
            'composition_rules' => ['Alterna pesos visuales y encuadres asimétricos.', 'Usa el color para guiar la lectura.'],
            'avoid' => ['plantilla corporativa genérica', 'simetría rígida', 'efectos decorativos obsoletos'],
        ],
        'infographic' => [
            'description' => 'Explica relaciones, procesos y datos mediante estructura visual.',
            'heading_font' => 'Aptos Display', 'body_font' => 'Aptos', 'geometry' => 'diagrammatic',
            'traits' => ['Procesos visibles', 'Cifras destacadas', 'Conectores claros'],
            'composition_rules' => ['Convierte secuencias y relaciones en diagramas editables.', 'Usa gráficos únicamente con datos reales.'],
            'avoid' => ['gráficos inventados', 'texto como imagen', 'decoración sin significado'],
        ],
        'youth' => [
            'description' => 'Cercano y enérgico para cursos mayores, sin perder rigor.',
            'heading_font' => 'Trebuchet MS', 'body_font' => 'Aptos', 'geometry' => 'energetic',
            'traits' => ['Títulos fuertes', 'Ritmo visual', 'Contraste expresivo'],
            'composition_rules' => ['Usa escala, diagonales suaves y acentos vivos.', 'Mantén lenguaje visual maduro y legible.'],
            'avoid' => ['estética infantil', 'jerga forzada', 'neón sobre fondos poco legibles'],
        ],
        'children' => [
            'description' => 'Lúdico, cálido y concreto para párvulos y primer ciclo básico.',
            'heading_font' => 'Trebuchet MS', 'body_font' => 'Trebuchet MS', 'geometry' => 'playful',
            'traits' => ['Formas amables', 'Color cálido', 'Lectura grande', 'Recursos concretos'],
            'composition_rules' => ['Usa formas redondeadas, recorridos visuales simples y siluetas variadas.', 'Aumenta tamaños, reduce densidad y deja espacio generoso entre elementos.', 'Representa conceptos con escenas, rutas, personajes abstractos u objetos concretos apropiados para la edad.', 'Mantén una energía alegre sin sacrificar contraste ni legibilidad.'],
            'avoid' => ['paneles institucionales', 'tableros corporativos', 'paleta turquesa apagada dominante', 'mapa conceptual repetido', 'texto pequeño', 'bloques densos'],
        ],
    ],
];
