<?php

return [
    'calendar_year' => 2026,
    'source_document_name' => 'PLAN DE GESTIÓN DE LA CONVIVENCIA ESCOLAR 2026 opción.docx',
    'source_document_sha256' => '37a824f59b19cf1d1671b509de02f168188bf3bf9ffb0c120db69c2f1b0c0a33',
    'name' => 'Plan de Gestión de la Convivencia Escolar 2026',
    'general_objective' => 'Promover durante 2026 una convivencia escolar basada en el buen trato, la acogida, la prevención, la participación y la resolución pacífica de conflictos.',
    'specific_objectives' => [
        'Implementar un protocolo institucional de acogida para estudiantes y familias nuevas.',
        'Fortalecer la resolución pacífica y alternativa de conflictos antes de recurrir a medidas sancionatorias.',
        'Desarrollar acciones preventivas y formativas para estudiantes, familias y funcionarios.',
        'Evaluar periódicamente el clima escolar y el cumplimiento de los plazos reglamentarios.',
    ],
    'resources_required' => 'Espacios institucionales, material formativo, instrumentos de asistencia y evaluación, coordinación del Equipo Directivo y del Equipo de Convivencia.',
    'indicators_summary' => 'Mediación de conflictos menores; participación de apoderados; cumplimiento de plazos de denuncia; percepción de clima escolar.',
    'verification_means_summary' => 'Registros de mediación, listas de asistencia, bitácoras de cumplimiento, encuestas de clima, actas y evidencias de cada actividad.',
    'status' => 'borrador',
    'starts_on' => '2026-03-01',
    'ends_on' => '2026-12-31',
    'observations' => 'Contenido precargado desde el documento institucional recibido. Las fechas exactas, responsables y recursos de cada acción deben confirmarse antes de publicar la versión vigente.',
    'institutional_protocol' => [
        [
            'title' => 'Bienvenida inicial',
            'description' => 'El primer día de clases, el Equipo Directivo recibirá a las familias nuevas en el salón principal para una charla sobre la identidad carmelitana.',
            'responsible' => 'Equipo Directivo',
            'timing' => 'Primer día de clases',
            'requirements' => null,
        ],
        [
            'title' => 'Programa Hermana Mayor',
            'description' => 'A cada estudiante nueva se le asignará una compañera de un nivel superior o del mismo curso con antigüedad para acompañarla en recreos y almuerzos.',
            'responsible' => 'Equipo de Convivencia y comunidad educativa',
            'timing' => 'Primera semana',
            'requirements' => 'Asignar y registrar a la estudiante acompañante.',
        ],
        [
            'title' => 'Recepción de almuerzos desde el hogar',
            'description' => 'Las familias podrán entregar almuerzos en Portería entre las 12:00 y las 12:45 horas.',
            'responsible' => 'Portería',
            'timing' => '12:00 a 12:45 horas',
            'requirements' => 'El envase debe ser térmico y estar rotulado con nombre y curso. El apoderado debe retirarse inmediatamente después de la entrega.',
        ],
    ],
    'evaluation_indicators' => [
        [
            'code' => 'KPI-01',
            'title' => 'Resolución alternativa',
            'description' => 'Conflictos menores resueltos mediante mediación antes de pasar a sanción.',
            'target_value' => 70,
            'target_unit' => '%',
            'frequency' => 'Trimestral',
            'verification_source' => 'Registros de mediación y expedientes de convivencia.',
        ],
        [
            'code' => 'KPI-02',
            'title' => 'Participación de apoderados',
            'description' => 'Asistencia de apoderados a los talleres formativos programados.',
            'target_value' => 60,
            'target_unit' => '%',
            'frequency' => 'Por actividad',
            'verification_source' => 'Listas de asistencia y actas de talleres.',
        ],
        [
            'code' => 'KPI-03',
            'title' => 'Eficacia legal',
            'description' => 'Cumplimiento de plazos de denuncia de 24 horas en casos de vulneración de derechos.',
            'target_value' => 100,
            'target_unit' => '%',
            'frequency' => 'Por caso',
            'verification_source' => 'Bitácoras, denuncias y activaciones de protocolos.',
        ],
        [
            'code' => 'KPI-04',
            'title' => 'Satisfacción',
            'description' => 'Nota promedio de la encuesta de percepción de clima escolar de fin de año.',
            'target_value' => 6.0,
            'target_unit' => 'nota',
            'frequency' => 'Anual',
            'verification_source' => 'Encuesta de percepción de clima escolar.',
        ],
    ],
    'regulatory_linkage_text' => 'VINCULACIÓN DEL PLAN DE GESTIÓN CON EL RÉGIMEN DISCIPLINARIO: El presente Plan de Gestión de la Convivencia Escolar es un instrumento vinculante para toda la comunidad. En caso de que una estudiante incurra en faltas Graves o Gravísimas, la Dirección del Colegio, en conjunto con el Equipo de Convivencia, podrá determinar como Medida Reparatoria Obligatoria la asistencia y cumplimiento de actividades específicas contempladas en este cronograma. El incumplimiento de la medida formativa o reparatoria por parte de la estudiante o la falta de apoyo del apoderado en este proceso, se considerará una vulneración a las normas de convivencia y un agravante en el historial disciplinario, lo que facultará al establecimiento para aplicar medidas sancionatorias superiores según el debido proceso establecido en este RICE.',
    'regulatory_review_required' => true,
    'actions' => [
        ['month' => 3, 'weight' => 10, 'type' => 'promocional', 'title' => 'Jornada de Inducción y Protocolo de Acogida', 'audience' => 'Estudiantes nuevas y familias'],
        ['month' => 4, 'weight' => 10, 'type' => 'promocional', 'title' => 'Mes de la Convivencia El Valor del Buen Trato', 'audience' => 'Toda la comunidad'],
        ['month' => 5, 'weight' => 10, 'type' => 'formativa', 'title' => 'Taller de Resolución Pacífica de Conflictos', 'audience' => 'Estudiantes de 5° básico a IV medio'],
        ['month' => 6, 'weight' => 10, 'type' => 'preventiva', 'title' => 'Capacitación Ley Karin y Prevención de Acoso Laboral', 'audience' => 'Docentes y asistentes'],
        ['month' => 7, 'weight' => 10, 'type' => 'promocional', 'title' => 'Feria de la Amistad y Evaluación de Clima Semestral', 'audience' => 'Estudiantes y funcionarios'],
        ['month' => 8, 'weight' => 10, 'type' => 'preventiva', 'title' => 'Jornada de Prevención de Ideación Suicida y Autocuidado', 'audience' => 'Docentes y apoderados'],
        ['month' => 9, 'weight' => 10, 'type' => 'promocional', 'title' => 'Encuentro de Chilenidad Convivencia y Tradición', 'audience' => 'Toda la comunidad'],
        ['month' => 10, 'weight' => 10, 'type' => 'preventiva', 'title' => 'Taller de Uso Responsable de Redes Sociales y Ciberacoso', 'audience' => 'Estudiantes y padres'],
        ['month' => 11, 'weight' => 10, 'type' => 'promocional', 'title' => 'Premiación Embajadoras de la Paz', 'audience' => 'Estudiantes destacadas'],
        ['month' => 12, 'weight' => 10, 'type' => 'formativa', 'title' => 'Evaluación Final y Actualización RICE 2027', 'audience' => 'Consejo Escolar'],
    ],
];
