<?php

return [
    'sources' => [
        'legacy_gradebook' => [
            'label' => 'Libro digital anterior',
            'description' => 'Catálogo transcrito desde las capturas institucionales entregadas el 22-08-2026.',
            'groups' => [
                [
                    'code' => 'basica',
                    'label' => 'Enseñanza Básica',
                    'education_type' => 'basica',
                    'subjects' => [
                        'Artes Visuales',
                        'Biología',
                        'Ciencias Naturales',
                        'Educación Física y Salud',
                        'Física',
                        'Historia, Geografía y Ciencias Sociales',
                        'Idioma Extranjero: Inglés',
                        'Idioma Extranjero: Inglés (Alternativo)',
                        'Lengua Indígena: Aymara',
                        'Lengua Indígena: Mapuzugun',
                        'Lengua Indígena: Quechua',
                        'Lengua Indígena: Rapa Nui',
                        'Lengua y Cultura de los Pueblos Originarios Ancestrales: Interculturalidad',
                        'Lengua y Cultura de los Pueblos Originarios Ancestrales: Pueblo Aymara',
                        'Lengua y Cultura de los Pueblos Originarios Ancestrales: Pueblo Colla',
                        'Lengua y Cultura de los Pueblos Originarios Ancestrales: Pueblo Diaguita',
                        'Lengua y Cultura de los Pueblos Originarios Ancestrales: Pueblo Kawésqar',
                        'Lengua y Cultura de los Pueblos Originarios Ancestrales: Pueblo Lickanantay',
                        'Lengua y Cultura de los Pueblos Originarios Ancestrales: Pueblo Mapuche',
                        'Lengua y Cultura de los Pueblos Originarios Ancestrales: Pueblo Quechua',
                        'Lengua y Cultura de los Pueblos Originarios Ancestrales: Pueblo Rapa Nui',
                        'Lengua y Cultura de los Pueblos Originarios Ancestrales: Pueblo Yagán',
                        'Lengua y Literatura',
                        'Lenguaje y Comunicación',
                        'Matemática',
                        'Música',
                        'Orientación',
                        'Química',
                        'Religión (Católica)',
                        'Religión (Evangélica)',
                        'Tecnología',
                    ],
                ],
                [
                    'code' => 'media_plan_comun',
                    'label' => 'Enseñanza Media · Plan común',
                    'education_type' => 'media',
                    'subjects' => [
                        'Artes Visuales',
                        'Artes: Danza',
                        'Artes: Teatro',
                        'Biología',
                        'Ciencias Naturales',
                        'Ciencias para la Ciudadanía',
                        'Ciencias para la ciudadanía: Ambiente y sostenibilidad',
                        'Ciencias para la ciudadanía: Bienestar y salud',
                        'Ciencias para la ciudadanía: Seguridad, Prevención y Autocuidado',
                        'Ciencias para la ciudadanía: Tecnología y Sociedad',
                        'Educación Ciudadana',
                        'Educación Física y Salud',
                        'Educación Física y Salud 1',
                        'Educación Física y Salud 2',
                        'Filosofía',
                        'Filosofía y Psicología',
                        'Física',
                        'Historia, Geografía y Ciencias Sociales',
                        'Historia, geografía y ciencias sociales: Chile y la Región Latinoamericana',
                        'Historia, geografía y ciencias sociales: Mundo global',
                        'Idioma Extranjero: Inglés',
                        'Idioma Extranjero: Inglés (Alternativo)',
                        'Lengua y Literatura',
                        'Matemática',
                        'Música',
                        'Orientación',
                        'Química',
                        'Religión (Católica)',
                        'Religión (Evangélica)',
                        'Taller de orientación Decisión vocacional y proyecto de vida',
                        'Taller de orientación Factores protectores y de riesgo personales y sociales',
                        'Taller de orientación Planificación y metas',
                        'Taller de orientación Vínculos y relaciones interpersonales',
                        'Tecnología',
                    ],
                ],
                [
                    'code' => 'media_hc_3_4',
                    'label' => 'Enseñanza Media HC · 3° y 4°',
                    'education_type' => 'media',
                    'subjects' => [
                        'Algebra y Modelos Analíticos',
                        'Arte: Diseño y arquitectura',
                        'Artes: Artes visuales, audiovisuales y multimediales',
                        'Artes: Creación y composición musical',
                        'Artes: Interpretación Musical',
                        'Artes: Interpretación y creación en Danza',
                        'Artes: Interpretación y creación en Teatro',
                        'Artes: Teatro',
                        'Biología celular y molecular',
                        'Biología de los ecosistemas',
                        'Ciencias de la Salud',
                        'Deportes y Actividades de Expresión Motriz',
                        'Educación física y salud: Ciencias del ejercicio físico y deportivo',
                        'Educación física y salud: Expresión Corporal',
                        'Educación física y salud: Promoción de estilos de vida activos y saludables',
                        'Evolución, ecología y ambiente',
                        'Filosofía: Estética',
                        'Filosofía: Filosofía Política',
                        'Filosofía: Seminario de Filosofía',
                        'Fisica Mecanica',
                        'Física',
                        'Historia, geografía y ciencias sociales: Chile y la Región Latinoamericana',
                        'Historia, geografía y ciencias sociales: Comprensión histórica del presente',
                        'Historia, geografía y ciencias sociales: Economía y sociedad',
                        'Historia, geografía y ciencias sociales: Geografía territorio y desafíos socioambientales',
                        'Historia, geografía y ciencias sociales: Mundo global',
                        'Idioma Extranjero: Inglés',
                        'Lengua y literatura: Lectura y escritura especializadas',
                        'Lengua y literatura: Participación y argumentación en democracia',
                        'Lengua y literatura: Taller de Literatura',
                        'Matemática: Pensamiento computacional y programación',
                        'Matemática: Probabilidades y estadísticas descriptiva e inferencial',
                        'Matemáticas: Geometría 3D',
                        'Matemáticas: Límites derivadas e integrales',
                        'Materiales e insumos de la industria gráfica',
                        'Música',
                        'Química',
                        'Química Orígenes e Historia',
                        'Taller de orientación Decisión vocacional y proyecto de vida',
                        'Taller de orientación Factores protectores y de riesgo personales y sociales',
                        'Taller de orientación Planificación y metas',
                        'Taller de orientación Vínculos y relaciones interpersonales',
                        'Tecnología',
                    ],
                ],
                [
                    'code' => 'institucionales',
                    'label' => 'Asignaturas creadas en el establecimiento',
                    'education_type' => 'all',
                    'subjects' => [
                        'ACADEMIA DE INGLÉS',
                        'Artes Visuales y Música',
                        'BANDAS',
                        'BASQUETBOL FORMATIVO',
                        'BASQUETBOL SELECCIÓN',
                        'BRIGOLAGE',
                        'Ciencias para la Ciudadanía',
                        'CIRCENSE',
                        'Comprensión Sociocultural',
                        'Consejo de Curso',
                        'CUERPO EN MOVIMIENTO',
                        'DIBUJO',
                        'Ed. Física',
                        'Educación Ciudadana',
                        'Electivo',
                        'Exp. Entorno Natural',
                        'FUTBOL',
                        'HANDBALL',
                        'JUEGOS DE MESA',
                        'Lenguajes Artísticos',
                        'Lenguaje Verbal',
                        'Lenguaje y Comunicación',
                        'Orientación',
                        'ORQUESTA LATINOAMERICANA',
                        'Pensamiento matematico',
                        'PINTURA',
                        'PLAY WITH ME!',
                        'POLIJUEGOS',
                        'PTU BIOLOGÍA',
                        'PTU FÍSICA',
                        'PTU HISTORIA',
                        'PTU LENGUAJE',
                        'PTU MATEMÁTICA',
                        'PTU QUÍMICA',
                        'Quimica II',
                        'Quimica Profundización',
                        'Taller de Habilidades',
                        'VIOLÍN',
                        'VOCES',
                        'VOLEIBOL',
                        'ZUMBA',
                    ],
                ],
            ],
        ],
    ],
];
