<?php

namespace App\Models\LibroDigital;

use Illuminate\Database\Eloquent\Model;

abstract class LibroDigitalModel extends Model
{
    /**
     * Validation and authorization are enforced at the service/request boundary.
     * Internal and public identifiers are generated by the database/model and
     * cannot be overwritten through mass assignment.
     *
     * @var list<string>
     */
    protected $guarded = ['id', 'public_id'];
}
