import axios from "axios";
const base = "/api/messaging";
export default {
  config: () => axios.get(`${base}/config`),
  summary: () => axios.get(`${base}/summary`),
  conversations: (params = {}) => axios.get(`${base}/conversations`, { params }),
  conversation: (id) => axios.get(`${base}/conversations/${id}`),
  messages: (id, params = {}) => axios.get(`${base}/conversations/${id}/messages`, { params }),
  message: (id) => axios.get(`${base}/messages/${id}`),
  send: (id, payload) => axios.post(`${base}/conversations/${id}/messages`, payload),
  direct: (userId) => axios.post(`${base}/conversations/direct`, { user_id: userId }),
  group: (payload) => axios.post(`${base}/conversations/group`, payload),
  updateConversation: (id, payload) => axios.patch(`${base}/conversations/${id}`, payload),
  addParticipants: (id, userIds) => axios.post(`${base}/conversations/${id}/participants`, { user_ids: userIds }),
  removeParticipant: (id, userId) => axios.delete(`${base}/conversations/${id}/participants/${userId}`),
  updateParticipant: (id, userId, payload) => axios.patch(`${base}/conversations/${id}/participants/${userId}`, payload),
  transferOwnership: (id, userId) => axios.post(`${base}/conversations/${id}/transfer-ownership`, { user_id: userId }),
  setLock: (id, locked) => locked ? axios.post(`${base}/conversations/${id}/lock`) : axios.delete(`${base}/conversations/${id}/lock`),
  users: (query) => axios.get(`${base}/users/search`, { params: { query } }),
  read: (conversationId, messageId) => axios.post(`${base}/conversations/${conversationId}/read`, { through_message_id: messageId }),
  acknowledge: (messageId, comment) => axios.post(`${base}/messages/${messageId}/acknowledge`, { comment }),
  receipts: (messageId) => axios.get(`${base}/messages/${messageId}/receipts`),
  upload: (file, onUploadProgress) => { const body = new FormData(); body.append("file", file); return axios.post(`${base}/uploads`, body, { onUploadProgress }); },
  removeUpload: (token) => axios.delete(`${base}/uploads/${token}`),
  react: (messageId, reaction) => axios.post(`${base}/messages/${messageId}/reactions`, { reaction }),
  unreact: (messageId, reaction) => axios.delete(`${base}/messages/${messageId}/reactions/${encodeURIComponent(reaction)}`),
};
